### ISSUE TITLE
Enhancements to start up process

### ISSUE THREAD

**Issue by mintiayields** [near/nearcore#6011] opened 2022-01-06 18:47 UTC
Currently neard will start up, initialize, check database, connect to peers, catch up, start validating.
Is it possible to launch some processes asynchronously? For instance connecting to peers may be parallel to opening database, right? Also it could make sense to use commands that will skip certain validations at startup, for example "restart" command may tell neard that it is starting up on fresh recent data, thus it may skip some first start routines.
This can reduce downtime of a node.

**Comment by bowenwang1996** [comment] 2022-01-07 19:07
When neard opens database it will first check whether migrations are needed. Also network code relies on database access as well, so I don't think that could be changed.

> Also it could make sense to use commands that will skip certain validations at startup, for example "restart" command may tell neard that it is starting up on fresh recent data, thus it may skip some first start routines.

Indeed. I think @nikurt is working on that

**Comment by nikurt** [comment] 2022-01-11 10:31
Let me mark this as a duplicate of #4791

**Closed by nikurt** 2022-01-11 10:31 UTC
Labels: C-enhancement, T-nodeX
