### ISSUE TITLE
Move towards a better way to update RuntimeConfig

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#4649] opened 2021-08-06 17:46 UTC
Currently updating runtime config is quite painful and usually involves adding more structs and code to the database. While there are discussions about long-terms plans to potentially [move all protocol configs to a contract](https://gov.near.org/t/store-protocol-config-in-a-contract/2105), it is likely not going to be implemented any time soon. As a result, we should figure out a better way to do this in the meantime. After a discussion with @matklad, we agreed that it is better to move most of the config to data, i.e, some file that we can read from and write to. More specifically, for each change of config, we generate a new config file with all the parameters and their values. Globally we can maintain a `BTreeMap<ProtocolVersion, RuntimeConfig>` to determine at runtime which config to use. 

Some considerations here:
* We eventually want to do this for the entirety of protocol config (what is `GenesisConfig` now), but we can start with runtime config to make the change more incremental and easier to implement.
* The format of the config files needs to be decided. For now I think json is fine. @matklad has some other ideas though.
* When new fields are added in a protocol change, we need to be able to handle that.

**Comment by bowenwang1996** [comment] 2021-08-06 17:47
This is also somewhat related to #4447. cc @posvyatokum

**Comment by matklad** [comment] 2021-09-24 11:55
I suggest prioritizing removal of 

https://github.com/near/nearcore/blob/721a581d85b15813c3356f0a694002f1dac599d3/core/primitives/src/runtime/config.rs#L52-L98

It fully duplicates `RuntimeConfigStore` so it's pure technical dept. As we've introduced both `RuntimeConfigStore` and `ActualRuntimeConfig` relatively recently, fixing this *now* would be easier, as the relevant code is still in mental L1 cache for some people.

**Comment by matklad** [comment] 2021-12-23 13:21
@Longarithm let's close the issue? I think this is mostly done? There's probably some specific follow-ups, but they are worth opening separate issues for.

**Comment by bowenwang1996** [comment] 2022-03-23 22:47
@Longarithm any update on this?

**Comment by Longarithm** [comment] 2022-03-23 22:55
The issue is actually resolved, I forgot to close it.

**Closed by Longarithm** 2022-03-23 22:55 UTC
Labels: A-transaction-runtime, T-core
