### ISSUE TITLE
Move EpochManager into Client

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#1617] opened 2019-11-01 16:30 UTC
Currently EpochManager is owned by NightshadeRuntime, which breaks a bunch of abstractions making runtime very aware of blocks and other chain specific constructions.
Moving EpochManager into Client, and removing from RuntimeAdapter will provide way cleaner interface and might even reduce locking on `runtime_adapter` Arc.

The only constrain (and why it was done currently) is that tracking shards is recoded in the runtime hense "care_about_shard" and "will_about_shard" depend on that and on EpochManager.

**Comment by bowenwang1996** [comment] 2021-07-01 23:17
We might not want to pursue this path if we plan to make epoch manager a contract.

**Comment by bowenwang1996** [comment] 2021-07-02 14:43
Duplicate of #2745

**Closed by bowenwang1996** 2021-07-02 14:43 UTC
Labels: A-chain, C-housekeeping
