### ISSUE TITLE
Add `estimateGas` to the JSON RPC

### ISSUE THREAD

**Issue by djsatok** [near/nearcore#4002] opened 2021-02-24 16:01 UTC
Ethereum JSON RPC has a very convenient endpoint `eth_estimateGas`, see [here](https://eth.wiki/json-rpc/api). This endpoint is used for estimating the amount of gas that a transaction execution may require. This is a very useful feature that enables the following flow of the usage of `ethers.js` library:

``` typescript
const provider = new ethers.providers.JsonRpcProvider(jsonRpc);
const signer = new ethers.Wallet(privateKey, provider);
const erc20 = new ethers.Contract(tokenAddress, erc20Abi, signer);
const approveTx = await erc20.approve(recipientAddress, ethers.BigNumber.from(depositAmount));
```

In the last call, `ethers.js` is using `eth_estimateGas` to calculate the appropriate amount of gas that is to be attached to the transaction. A user is able to overload this amount with his value.

At the moment sending a NEAR transaction looks quite similar with exception of the need of specifying of the attached gas:

``` typescript
const keyStore = new nearAPI.keyStores.UnencryptedFileSystemKeyStore(keyStoreString);
const near = await nearAPI.connect({deps: {keyStore}, nodeUrl: jsonRpc, networkId: network});
const account = await near.account(accountString);
const connector = new nearAPI.Contract(account, connectorAccount, {viewMethods: [], changeMethods:["deposit"]});
const val1 = new BN('300000000000000'); // Gas limit
const val2 = new BN('100000000000000000000').mul(new BN('600')); // Attached payment to pay for the storage
await connector.deposit(proof, val1, val2);
```

Adding `estimateGas` RPC will make the above calls  much simple. Obviously after addition of the RPC endpoint, `near-api-js` should be updated to use it.
Also, it would be a good thing to get an estimation of the required deposit for the storage payment (that potentially can be split between multiple contracts), so the `val2` from the example above can be also automatically calculated.

**Comment by frol** [comment] 2021-03-18 20:06
Duplicate of #3448

**Closed by frol** 2021-03-18 20:06 UTC
Labels: RPC, enhancement
