### ISSUE TITLE
Update RPC error schema

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#2536] opened 2020-04-28 00:54 UTC
According to https://github.com/nearprotocol/nearcore/issues/2518#issuecomment-619452654, when we query a transaction and it doesn't exist, we do not return a structured error, which causes problems in downstream applications. We need to update the rpc error schema to make the errors structured.

**Comment by nearmax** [comment] 2020-05-06 18:07
@bowenwang1996  Please, clarify that this issue is about updating the schema.

**Comment by bowenwang1996** [comment] 2020-05-06 19:18
Updated

**Comment by nearmax** [comment] 2020-05-17 02:50
@fckt how much time do you think it is actually going to take?

**Comment by fckt** [comment] 2020-05-18 12:35
No more than 1 day if no surprises.

**Comment by frol** [comment] 2020-05-18 18:21
I am going to work on this together with https://github.com/nearprotocol/nearcore/issues/2652

**Comment by vgrichina** [comment] 2020-06-10 07:22
@frol any update on this? Looks like errors still returned like this: 
`{"jsonrpc":"2.0","error":{"code":-32000,"message":"Server error","data":"Timeout"},"id":139}`

**Comment by frol** [comment] 2020-06-10 08:01
@vgrichina I was grabbed into #2738. I will get back as soon as I can.

**Comment by ilblackdragon** [comment] 2020-06-30 13:21
@vgrichina You mentioned in the other issue this reproduction:
```
[I] ➜ http post https://rpc.betanet.nearprotocol.com jsonrpc=2.0 method=tx params:='["CqiBnYCRgkGV2odJPXJTBkoZHXjDNQFJKw7oRYWU1j6g", "betanet"]' id=dontcare
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 162
Content-Type: application/json
Date: Mon, 27 Apr 2020 23:14:13 GMT
Server: nginx/1.14.0 (Ubuntu)

{
    "error": {
        "code": -32000,
        "data": "Transaction CqiBnYCRgkGV2odJPXJTBkoZHXjDNQFJKw7oRYWU1j6g doesn't exist",
        "message": "Server error"
    },
    "id": "dontcare",
    "jsonrpc": "2.0"
}
```

What error format do you expect here?

**Comment by bowenwang1996** [comment] 2020-06-30 19:16
@ilblackdragon the idea is the the data field should be a json that has a field "type", like what we have for transactions https://github.com/nearprotocol/nearcore/blob/master/chain/jsonrpc/res/rpc_errors_schema.json

**Comment by damons** [comment] 2020-07-13 16:52
Moving to Phase 2. Will re-address when we get there.

**Comment by ilblackdragon** [comment] 2020-07-17 09:52
The scope of this issue covers all RPC errors, including missing blocks and chunks, tx, etc 
Currently only errors that are coming from transaction processing are structured and the rest are plain strings which also frequently missing context (like block was skipped in current chain vs garbage collected vs completely missing)

**Comment by frol** [comment] 2021-05-01 09:35
This issue is not relevant anymore. Structured JSONRPC errors required a huge revamp throughout the project, and we recently finished the internals refactoring, the last piece is left to expose the information through the JSON RPC boundary (tracking issue #2976)

**Closed by frol** 2021-05-01 09:35 UTC
Labels: RPC, enhancement
