### ISSUE TITLE
Flat storage doesn't support  genesis_state_from_dump

### ISSUE THREAD

**Issue by mm-near** [near/nearcore#8396] opened 2023-01-19 14:22 UTC
This is what breaks the state_sync_massive test.

The state_from_dump is loading data directly into Trie - and doesn't update flat storage.

**Comment by Longarithm** [comment] 2023-01-19 14:28
Duplicate of https://github.com/near/nearcore/issues/8322 :)

**Closed by Longarithm** 2023-01-19 14:28 UTC
