### ISSUE TITLE
RPC nodes falling out of sync

### ISSUE THREAD

**Issue by mhalambek** [near/nearcore#5112] opened 2021-11-02 14:09 UTC
RPC nodes on mainnet are lagging behind latest block. This is causing issues for users of wallet and other services which use RPC.

User reported errors from wallet
![image](https://user-images.githubusercontent.com/7011689/139862378-730f7e88-a3a2-4612-8865-5a7d5642e348.png)
![image (1)](https://user-images.githubusercontent.com/7011689/139862386-b65ed061-332b-48f8-8936-f4a5dfbcc865.png)

Grafana graph showing time it takes the node to reach latest block.
![2021-11-02-140632_1920x1080_scrot](https://user-images.githubusercontent.com/7011689/139863093-944e8b72-9d54-41bd-8cb1-4c8afbc25fc3.png)

Nearcore version 1.21.0

**Comment by evgenykuzyakov** [comment] 2021-11-02 22:31
I've also got errors from `near-cli` that marks transaction as `Expired`:

E.g. `ServerError: Transaction has expired`

I think the reason is the node is out of sync and rejects the transaction with the blockhash that is recent, but not synced yet.

I suggest to reply from such nodes with a different error. E.g. `OutOfSync` RPC error, so a client can retry the request to a different RPC node.

**Comment by nikurt** [comment] 2021-11-05 20:18
Based on the issue #4937 , dumped column `ColStateDlInfos` and it was empty.
The code: https://github.com/near/nearcore/compare/nikurt-col-dump?expand=1
Couldn't use `ldb` or `sst_dump` due to `too many files open` error.

**Comment by bowenwang1996** [comment] 2021-11-07 18:35
I looked a bit more into this issue. It appears to me that the issue is caused by nodes waiting sometimes too long for a chunk to arrive. I think we may need to prioritize #3863, #1689, and potentially #3890. cc @mzhangmzz

**Comment by nikurt** [comment] 2021-11-08 08:42
Extracted a few lines of log during an archival node switching back and forth between syncing and working:
[archive_rpc_sync_log.txt](https://github.com/near/nearcore/files/7495419/archive_rpc_sync_log.txt)

**Comment by nikurt** [comment] 2021-11-08 09:31
All cases of an Asian archival rpc node starting and finishing syncing:
[Uploading archive_rpc_sync_log.txt…]()

**Comment by nikurt** [comment] 2021-11-08 10:10
The node managed to fall 10 blocks behind merely 10 seconds after finishing the last sync: #52158507 -> #52158517
[big_gap.txt](https://github.com/near/nearcore/files/7496063/big_gap.txt)

**Comment by pmnoxx** [comment] 2021-11-10 07:35
I'll take a look

**Comment by pmnoxx** [comment] 2021-11-10 07:37
This does seem like an issue with routing 
```

Nov 08 08:05:14 public-v1-archive-mainnet-rpc-node-p3x5 sh[1942]: Nov 08 08:05:14.108 DEBUG network: None Drop signed message to Hash(`GC72RjNQpJuKMierihJ4bYaF7WMFQCYfPgadbRyGE3fA`) Reason RouteBackNotFound. Num known peers: 411 Message PartialChunkResponse(ChunkHash(`6Y2YYNUpp62uNQxAvo3a7LxfC4eLMDeXeoZisKHcPANx`), [84])
Nov 08 08:05:14 public-v1-archive-mainnet-rpc-node-p3x5 sh[1942]: Nov 08 08:05:14.131 DEBUG network: None Drop signed message to Hash(`C6Q52jRSJxnfuSn7TuoSbVXcEVM8DtpB2xikFDamzLVT`) Reason RouteBackNotFound. Num known peers: 411 Message PartialChunkResponse(ChunkHash(`DNEWNwDysCsAHg14vy6UdVQHvdSQHU1i6yxiDcanhieA`), [84])
```
We should add some more debug info to figure it out.

**Comment by pmnoxx** [comment] 2021-11-10 07:54
I notice a code path, where it's possible we will return to `PeerActor` list of peers to which we have no route to `highest_height_peers`.
I added printing an error when that happens.

https://github.com/near/nearcore/pull/5192

**Comment by bowenwang1996** [comment] 2022-01-24 15:21
This is supposed fixed in https://github.com/near/nearcore/pull/5747 and #5637

**Closed by bowenwang1996** 2022-01-24 15:21 UTC
Labels: C-bug, A-chain, A-RPC, T-nodeX
