### ISSUE TITLE
The order of ExecutionOutcomes

### ISSUE THREAD

**Issue by khorolets** [near/nearcore#3467] opened 2020-10-07 09:17 UTC
To properly implement accounts and access keys tracking (add, delete) in indexers we need to correct order of ExecutionOutcomes.

For example if in one block we have actions for the same `CreateAccount` and `DeleteAccount` we should create it and then delete it. But we have unordered outcomes so we might have try to delete account first and then create it what ends up in the wrong representation of the state in indexer.

How can we solve this?

/cc @frol @bowenwang1996 @mikhailOK @evgenykuzyakov

**Comment by frol** [comment] 2020-10-07 09:22
For the context, `ColOutcomesByBlockHash` stores the outcomes by block in as `HashSet`:

https://github.com/nearprotocol/nearcore/blob/b3bb1da661b374f9c13a28f3932bcb06ff076313/chain/chain/src/store.rs#L2584

Is there a way to store outcomes in their execution order? (well, from Indexer point of view, it does not care about how it is stored, it needs to retrieve them so they are sorted in their execution order)

**Comment by bowenwang1996** [comment] 2020-10-07 16:51
> Is there a way to store outcomes in their execution order? (well, from Indexer point of view, it does not care about how it is stored, it needs to retrieve them so they are sorted in their execution order)

Yes we can. The problem is that when we do the migration, trying to recover the order could be nontrivial if we had delayed receipts.

**Comment by frol** [comment] 2020-10-07 17:26
Well, at least you have some plan to recover the order while on the indexer side it does not appear to be feasible at all.

Meanwhile, Indexer for Explorer is going to be working at its best effort, but corner cases like adding and removing same keys/accounts in a single block/chunk/transaction/receipt may get corrupted. I believe other Indexer implementations may also require strict order of events.

I am assigning this issue to @nearmax for triage and reassignment in the future milestone.

**Comment by bowenwang1996** [comment] 2020-10-08 15:02
I thought about it again and it doesn't appear to be difficult to do. I can work on this if needed

**Comment by frol** [comment] 2020-10-08 15:07
@bowenwang1996 That would be greatly appreciated!

**Closed** 2020-10-28 23:48 UTC
Labels: enhancement, indexer, storage
