### ISSUE TITLE
Consider removing circular dependencies during tests

### ISSUE THREAD

**Issue by matklad** [near/nearcore#4357] opened 2021-06-09 13:25 UTC
At the moment, nearcore consists of a large number of crates which are relatively independent. However, there's one notable exception -- the `testlib` crates depends on majority of the crates, and almost every crate has `testlib` as a dev-dependency. That means that we have circular dependencies during tests. For example, if you are fixing a bug in `near-client` and run `cargo t -p near-client`, you'll be rebuilding `nearcore` and `near-json-rpc` as well. 

I think there's a benefit in removing `dev-dendencies` on `testlib`, and instead moving all tests which need access to testlib (and nearcore) from individual crates into the top-level `integration-tests` crate we have. Having tests for individual functionalities in a common uber-test crate might not look as pretty, but it'll faithfully reflect the physical architecture of our project. We should strive to test things in isolation, but we don't actually have such isolation today for many tests.

**Comment by bowenwang1996** [comment] 2021-07-15 20:02
Today I realized how annoying it is. I tried to debug some test in `near-client` and when I run the test with nightly protocol features, it resulted in the following error
```
error[E0574]: expected struct, variant or union type, found enum `BlockInfo`
   --> chain/epoch_manager/src/test_utils.rs:315:5
    |
315 |     BlockInfo {
    |     ^^^^^^^^^ not a struct, variant or union type
```
which is caused by `near-client` having `nearcore` as a dev-dependency and we cannot specify features for dev dependencies. This means that in order to run the test, I had to run `cargo test --workspace`, which is very slow.

**Comment by matklad** [comment] 2021-07-16 10:24
https://github.com/near/nearcore/issues/4470/ is probably a good isolated first-step herez

**Comment by matklad** [comment] 2021-08-13 12:25
@nikurt seems like this is not fully done yet: node-runtime and testlib still seem to depend on each other

* https://github.com/near/nearcore/blob/942e02daf7d75a94db51ef1c4ea9ef27aed459a4/test-utils/testlib/Cargo.toml#L30
* https://github.com/near/nearcore/blob/942e02daf7d75a94db51ef1c4ea9ef27aed459a4/runtime/runtime/Cargo.toml#L64

There's also small cycle between near_network and near_client.

**Comment by nikurt** [comment] 2021-08-17 14:37
Thanks @matklad , will take a look.

**Comment by matklad** [comment] 2021-08-18 12:06
Almost there :) There are couple of more cycles left. I use `rust-analyzer analysis-stats` to look for cycles, the output on master is

```
cyclic deps: near_network(CrateId(1057)) -> near_client(CrateId(1036)), alternative path: near_client(CrateId(1036)) -> near_chunks(CrateId(1035)) -> near_network(CrateId(1057))

cyclic deps: testlib(CrateId(1666)) -> near_client(CrateId(1036)), alternative path: near_client(CrateId(1036)) -> node_runtime(CrateId(1110)) -> testlib(CrateId(1666))

cyclic deps: testlib(CrateId(1666)) -> near_jsonrpc(CrateId(1048)), alternative path: near_jsonrpc(CrateId(1048)) -> near_client(CrateId(1036)) -> node_runtime(CrateId(1110)) -> testlib(CrateId(1666))
```

#4707 is a fix for the last two, haven't looked into the first one. And looks like #4707 became possible due to other refactors by @nikurt :tada:

**Comment by bowenwang1996** [comment] 2021-08-19 22:57
Fixed in https://github.com/near/nearcore/pull/4712

**Closed by bowenwang1996** 2021-08-19 22:57 UTC
Labels: C-housekeeping, A-testing, T-nodeX
