### ISSUE TITLE
Error during re-requesting partial encoded chunk 1.24.0-rc.1

### ISSUE THREAD

**Issue by mintiayields** [near/nearcore#6162] opened 2022-01-22 13:53 UTC
Getting these errors a lot:
Jan 22 16:33:27.227 ERROR chunks: Error during re-requesting partial encoded chunk. Cannot determine whether to request from an archival node, defaulting to not: DB Not Found Error: BfpLxsmTBjtxMhs1Hd5R155Nyv7k5R3HreQgEuA52Rtc
 Cause: Unknown
Jan 22 16:33:27.228 ERROR chunks: Error during requesting partial encoded chunk: DB Not Found Error: BfpLxsmTBjtxMhs1Hd5R155Nyv7k5R3HreQgEuA52Rtc
 Cause: Unknown

At Guildnet this does not prevent the node from validating. 
At Testnet this results in missed blocks and failure to synchronize. The node starts to fall behind and download headers/blocks and never comes out of this state unless restarted.

**Comment by bowenwang1996** [comment] 2022-01-22 20:15
Duplicate of #6100

**Closed by bowenwang1996** 2022-01-22 20:15 UTC
