### ISSUE TITLE
Peer connections unstable on 1.24.0-rc.1 (node will not catch up or fall back even while validating)

### ISSUE THREAD

**Issue by mintiayields** [near/nearcore#6140] opened 2022-01-20 15:23 UTC
Since the mentioned release testnet nodes are reported on Discord as being unable to catch up. My observations:
1. Node start well, connects to some 12-16 peers and starts to catch up
2. Occasionally it will lose connections to peers to some 5-7 and will stick at the same download percentage, meaning it receive as many blocks per second as the blockchain produces.
3. When/if number of peers grows the node will catch up well, and the contrary: peers drop - falls behind. One of my cases is I left it at 100 blocks behind to find it in the morning at 20000 (!) blocks behind with just 2 peers.
4. Node has sufficient peers, VALIDATES and loses peers to some 3-4 and falls behind right when validating!!!

**Comment by janewang** [comment] 2022-01-20 17:17
@mintiayields  Can you attach the log? Thanks

**Comment by janewang** [comment] 2022-01-20 17:18
cc @bowenwang1996 @nikurt

**Comment by mzhangmzz** [comment] 2022-01-20 18:01
cc @pmnoxx

**Comment by mintiayields** [comment] 2022-01-20 22:32
Here is the log for the latest two days.
[neard.log.gz](https://github.com/near/nearcore/files/7908911/neard.log.gz)

**Comment by mintiayields** [comment] 2022-01-20 22:34
Please, also note this kind of errors:
ERROR chunks: Error during re-requesting partial encoded chunk. Cannot determine whether to request from an archival node, defaulting to not: DB Not Found Error: 4t5CneFYJ4v8EYubz4S9d7RXBmWtpXoLdXZtVuDRMN7h
 Cause: Unknown
Jan 21 01:33:35.284 ERROR chunks: Error during requesting partial encoded chunk: DB Not Found Error: 4t5CneFYJ4v8EYubz4S9d7RXBmWtpXoLdXZtVuDRMN7h
May be related.

**Comment by mzhangmzz** [comment] 2022-01-21 00:05
@mintiayields Thanks for the log! 
That error message is benign, we are working on a fix for that now. 
It's interesting that your node lost connections to peers though. We will investigate there

**Comment by bowenwang1996** [comment] 2022-01-22 20:14
Duplicate of #6126

**Closed by bowenwang1996** 2022-01-22 20:14 UTC
Labels: C-bug, T-nodeX
