### ISSUE TITLE
Add CI test that checks that attempt publishing crates and compile them to Wasm

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#4379] opened 2021-06-18 21:38 UTC
Some of the crates in nearcore are made publishable to crates.io. This is done so that external tools like near-sdk-sim can use them without pulling cross-repo github dependency which frequently break.

Also, some of the crates need to be compilable to Wasm because they are used for test in near-sd-as.

Unfortunately, there are no CI checks that make sure this is correct, and PRs like this one https://github.com/near/nearcore/commit/d336b3fc1b9dc2167aa2eb9a89e24e4a2a09e27d#r52341955 can break the above invariants. We need to add the following checks into our CI:
* A dry-run attempt to publish publishable crates to crates.io;
* A Wasm compilation of certain crates.

**Comment by mina86** [comment] 2021-06-22 00:24
Adding a dry-run publish test won’t work at this stage.  Before such
check is added we need to:

* publish a new `near-primitives` release version 0.1.0 (alternatively
  update dependencies to in Cargo.toml to 0.1.0-pre.1),

* publish a new ‘near-vm-errors’ release which includes
  `protocol_feature_alt_bn128` feature and

* publish a new `near-vm-runner` release version 3.0.0,

* create a new `near-evm-runner` crate.

To be honest I’m sceptical that such test will actually be beneficial.
For example, it will force us to publish crates as soon as a new
feature is added to them.  Similarly, make new crates even if they’re
at a very early experimental stages.

**Comment by matklad** [comment] 2021-06-23 14:55
>Also, some of the crates need to be compilable to Wasm because they are used for test in near-sd-as.

Oh wow, I didn't realize that assembly script tests work by compiling our vmlogic to wasm to implement mocked blockchain in the javascript environment. That makes sense, but also indeed places a rather big constraint on what we are allowed to do in the relevant parts. 

Publishing to crates.io and wasm compatability are rather big asks, because the establish a boundary in the code. It's best if this boundary is physically reflected in code layout, rather than it being an informal agreement that "we publish this, this, and this crate, and we don't publish that crate". As such, I think the best long-term solution is to introduce a single umbrella crate for publishing & wasm compat. 

So, something like `nearcore-sim-api` crate in this repository would re-export vm-logic, vm-errors and everything else which is needed by use-cases outside of nearcore. This crate will have a readme explaining that this is a semi-public API of nearcore used by the simulators, it will have additional CI checks, and a reminder to not needlessly break its APIs. Long-term, we can even work on future-proofing this crate's API, so as to minimize catch up work by near-sdk-as / -sim.

That's a long-term solution though, because it requires changing existing consumers of already-published crates. Not sure what's the best near-term solution would be. I suspect it actually might be working towards the long-term solution? I bet the current APIs have already diverged enough to make upgrade of nearcore crates in near-sdk-as non-trivial, so we might as well try to introduce a proper boundary here?

cc @austinabell, @willemneal

**Comment by bowenwang1996** [comment] 2021-06-28 20:19
@matklad given what you said, should we close this issue and create a new one on the long term solution?

**Comment by mina86** [comment] 2021-07-05 17:47
@matklad, @nearmax, any decision here?

**Comment by matklad** [comment] 2021-07-06 13:29
I believe we are still in the state of confusion regarding this issue, no decision has been made, and the status-quo is self-contradictory. 

To reach a decision, we need input from devx team (cc @mikedotexe) on the following questions:

* Has the decision on [sandbox](https://gov.near.org/t/revisiting-contract-testing-framework/2920) have been reached (cc (@DiscRiskandBisque as product vision owner)? Are we going to maintain&develop our current testing infra, or are we freezing it as is, and focus all efforts on the sandbox?
* will `near-sdk-rs` update [its dependency](https://github.com/near/near-sdk-rs/blob/763e23c6108071c1a27056ee991360cc4b54128f/near-sdk/Cargo.toml#L27-L28) on `near-vm-logic` and `near-primitives-core`?
* will `near-sdk-sim` update [its dependencies](https://github.com/near/near-sdk-rs/blob/763e23c6108071c1a27056ee991360cc4b54128f/near-sdk-sim/Cargo.toml#L16-L23) on a bunch of nearcore crates?
* will `near-sdk-as` update [its dependencies](https://github.com/near/near-sdk-as/blob/df766de450aa77b37a4ba3bafa7d3d0bba1369fa/near-mock-vm/Cargo.toml#L23-L24) on `near-vm-logic` and `near-vm-errors`
* will `near-sdk-as` migrate to using `near-sdk-sim` compiled to wasm or host?

* Additionally, I've heard from @frol that there's a desire to share some nearcore code with projects that want to interact with nearcore RPC endpoints. Is there a write up somewhere describing what do we want to share exactly?

I suggest the following course of action:

* If we are unsure if we'd want to upgrade sdk deps on nearcore, let's do nothing and wait. If the need comes to publish the crates, we can fix publishing at that point. 
* if we think that we won't be using nearcore in sdks, then we can close this issue, and reconsider primitives/primitives-core split
* if we think that we will continue developing our current testing infra, then yes, we need to continue checking that vm-logic is publishable and compatible with wasm


Note that I believe that the issue is non-urgent -- there's no active work which is blocked on reaching the decision here.

**Comment by matklad** [comment] 2021-07-16 13:54
I suggest closing the issue (feel free to re-open if you strongly disagree).

* we still don't have specific understanding of what we want to publish. 
* we no longer need to compile stuff to wasm, sdk now [doesn't depend](https://github.com/near/near-sdk-rs/blob/932ebb58a8b5dbc727b9718dd50f5e13bd839a8f/near-sdk/Cargo.toml#L19-L35) on nearcore on wasm

It seems like it's less long-term work to setup publishing later, when we either know what exactly do we want to publish, or when we need to publish something ASAP.

**Closed by matklad** 2021-07-16 13:54 UTC
Labels: A-testing, S-blocked, T-nodeX
