### ISSUE TITLE
Compile error in macos(M1)

### ISSUE THREAD

**Issue by ci123chain** [near/nearcore#4995] opened 2021-10-13 02:21 UTC
run `make neard` got error:

```
error[E0425]: cannot find function `get_fault_info` in this scope
   --> /Users/tan/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/wasmer-runtime-core-near-0.18.2/src/fault.rs:304:21
    |
304 |         let fault = get_fault_info(siginfo as _, ucontext);
    |                     ^^^^^^^^^^^^^^ not found in this scope

   Compiling near-performance-metrics v0.1.0 (/Users/tan/Documents/work/rust/nearcore/utils/near-performance-metrics)
For more information about this error, try `rustc --explain E0425`.
error: could not compile `wasmer-runtime-core-near` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [neard] Error 101
```

**Comment by bowenwang1996** [comment] 2021-10-13 21:55
Duplicate of #3803

**Closed by bowenwang1996** 2021-10-13 21:55 UTC

**Comment by ivanproskuryakov** [comment] 2022-02-01 22:33
https://stackoverflow.com/a/66667245/2235085

**Comment by matklad** [comment] 2022-02-02 10:23
FWIW, we've landed preliminary support for M1 on master yesterday: https://github.com/near/nearcore/pull/6200
