### ISSUE TITLE
Couldn't build near-core as dependency for indexer service on m1 max.

### ISSUE THREAD

**Issue by ChzenChzen** [near/nearcore#6030] opened 2022-01-08 16:59 UTC
**Describe the bug**
Couldn't build near-indexer on MacBook m1 max.

**To Reproduce**
my crate setup:

`rust-toolchain.toml`
```
[toolchain]
channel = "stable-x86_64-apple-darwin"
```

```
rustup show
Default host: aarch64-apple-darwin
rustup home:  /Users/fomotoshi/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin (default)
stable-x86_64-apple-darwin
1.56.0-aarch64-apple-darwin
1.57.0-aarch64-apple-darwin

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (overridden by '/Users/fomotoshi/Documents/projects/near/toy_indexer/rust-toolchain.toml')
rustc 1.57.0 (f1edd0429 2021-11-29)
```

`Cargo.toml`
```
[package]
name = "toy_indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "=0.11.0-beta.2"
actix-rt = "=2.2.0"  # remove it once actix is upgraded to 0.11+
openssl-probe = { version = "0.1.4" }
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
tokio = { version = "1.15.0", features = ["sync"] }

near-indexer = { git = "https://github.com/near/nearcore" }
```

building error report:
```
...
error[E0425]: cannot find function `get_fault_info` in this scope
   --> /Users/fomotoshi/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-runtime-core-near-0.18.2/src/fault.rs:304:21
    |
304 |         let fault = get_fault_info(siginfo as _, ucontext);
    |                     ^^^^^^^^^^^^^^ not found in this scope

...

error: could not compile `wasmer-runtime-core-near` due to previous error
```

**Comment by bowenwang1996** [comment] 2022-01-17 17:27
Duplicate of #3803

**Closed by bowenwang1996** 2022-01-17 17:27 UTC
Labels: T-contract-runtime
