### ISSUE TITLE
`neard init and run` broken on nightly after sharding config changes

### ISSUE THREAD

**Issue by chefsale** [near/nearcore#4992] opened 2021-10-12 21:11 UTC
To reproduce please run:
```
sandi@sandi-ThinkPad-X1-Carbon-7th ~> ./neard init
Oct 12 22:10:56.118  INFO neard: Version: trunk, Build: 7c77e3b0, Latest Protocol: 122
Oct 12 22:10:56.120  INFO near: Generated node key, validator key, genesis file in /home/sandi/.near
sandi@sandi-ThinkPad-X1-Carbon-7th ~> ./neard run
Oct 12 22:11:00.335  INFO neard: Version: trunk, Build: 7c77e3b0, Latest Protocol: 122
Oct 12 22:11:00.336  INFO near_chain_configs::genesis_config: load simple nightshade shard layout from genesis config
Oct 12 22:11:00.338  INFO near: Did not find "/home/sandi/.near/data" path, will be creating new store database
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `EpochConfig { epoch_length: 500, num_block_producer_seats: 50, num_block_producer_seats_per_shard: [50], avg_hidden_validator_seats_per_shard: [0], block_producer_kickout_threshold: 90, chunk_producer_kickout_threshold: 90, online_min_threshold: Ratio { numer: 9, denom: 10 }, online_max_threshold: Ratio { numer: 99, denom: 100 }, fishermen_threshold: 10000000000000000000000000, minimum_stake_divisor: 10, protocol_upgrade_stake_threshold: Ratio { numer: 4, denom: 5 }, protocol_upgrade_num_epochs: 2, shard_layout: V0(ShardLayoutV0 { num_shards: 1, version: 0 }), validator_selection_config: ValidatorSelectionConfig { num_chunk_only_producer_seats: 300, minimum_validators_per_shard: 1, minimum_stake_ratio: Ratio { numer: 1, denom: 6250 } } }`,
 right: `EpochConfig { epoch_length: 500, num_block_producer_seats: 50, num_block_producer_seats_per_shard: [50, 50, 50, 50], avg_hidden_validator_seats_per_shard: [0, 0, 0, 0], block_producer_kickout_threshold: 90, chunk_producer_kickout_threshold: 90, online_min_threshold: Ratio { numer: 9, denom: 10 }, online_max_threshold: Ratio { numer: 99, denom: 100 }, fishermen_threshold: 10000000000000000000000000, minimum_stake_divisor: 10, protocol_upgrade_stake_threshold: Ratio { numer: 4, denom: 5 }, protocol_upgrade_num_epochs: 2, shard_layout: V1(ShardLayoutV1 { fixed_shards: [], boundary_accounts: [AccountId("aurora"), AccountId("aurora-0"), AccountId("kkuuue2akv_1630967379.near")], shards_split_map: Some([[0, 1, 2, 3]]), to_parent_shard_map: Some([0, 0, 0, 0]), version: 1 }), validator_selection_config: ValidatorSelectionConfig { num_chunk_only_producer_seats: 300, minimum_validators_per_shard: 1, minimum_stake_ratio: Ratio { numer: 1, denom: 6250 } } }`', core/chain-configs/src/genesis_config.rs:250:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by mina86** [comment] 2021-10-12 23:33
Did this got fixed in the meanwhile? I cannot reproduce it:

    $ cargo build --release -pneard --bin neard
    ...
    $ ./target/release/neard --home=/tmp/neard-teast init
    Oct 13 01:29:37.861  INFO neard: Version: trunk, Build: 7c77e3b0, Latest Protocol: 48
    Oct 13 01:29:37.861  INFO near: Generated node key, validator key, genesis file in /tmp/neard-teast
    $ ./target/release/neard --home=/tmp/neard-teast run --disable-rpc
    Oct 13 01:29:42.229  INFO neard: Version: trunk, Build: 7c77e3b0, Latest Protocol: 48
    Oct 13 01:29:42.229  INFO near: Did not find "/tmp/neard-teast/data" path, will be creating new store database
    thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 98, kind: AddrInUse, message: "Address already in use" }', chain/network/src/peer_manager.rs:1405:45
    Oct 13 01:29:52.438  INFO stats: #      16 H3an6yM7quMZPQCDRFXny22JUYAV9SAuvq7sedhECmgf V/1  0/0/40 peers ⬇ 0 B/s ⬆ 0 B/s 1.60 bps 0 gas/s CPU: 0%, Mem: 0 B
    ^C

The binary does fail if I try to set number of shards but the error is
different than given:

    $ rm -rf /tmp/neard-teast/
    $ ./target/release/neard --home=/tmp/neard-teast init --num-shards 4
    Oct 13 01:30:23.589  INFO neard: Version: trunk, Build: 7c77e3b0, Latest Protocol: 48
    Oct 13 01:30:23.589  INFO near: Generated node key, validator key, genesis file in /tmp/neard-teast
    $ ./target/release/neard --home=/tmp/neard-teast run --disable-rpc
    Oct 13 01:30:27.213  INFO neard: Version: trunk, Build: 7c77e3b0, Latest Protocol: 48
    Oct 13 01:30:27.214  INFO near: Did not find "/tmp/neard-teast/data" path, will be creating new store database
    thread 'main' panicked at 'assertion failed: `(left == right)`
      left: `1`,
     right: `4`: genesis config shard_layout and num_block_producer_seats_per_shard indicate inconsistent number of shards 1 vs 4', nearcore/src/runtime/mod.rs:191:9

**Comment by chefsale** [comment] 2021-10-13 00:33
Happens only on nightly release.

**Closed as completed** 2021-10-14 01:31 UTC
