### ISSUE TITLE
Investigate network bottleneck when there are many shards

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#3438] opened 2020-10-02 16:09 UTC
@birchmd did some preliminary investigation to understand the performance of data transmission when there are many shards. The experiment was done by creating chunks with only garbage data and skip applying chunks to see the scalability on the network level. The result is as follows:

![image (1)](https://user-images.githubusercontent.com/13601726/94944551-438b4580-048e-11eb-9424-05ef27402999.png)

As we can see, when there are more than 20 shards, the bps becomes quite low. We need to understand why it is the case and what we can do to address this issue.

**Comment by birchmd** [comment] 2020-10-29 19:14
Summary of work done on this ticket:

* The result of the previous test (data in the plot from the description) was reproduced with the most recent code; the bps still decays to unacceptably low levels.

* To ensure the cause did not have to do with nodes producing / consuming multiple chunks we made sure there were exactly as many seats as validators, this did not help.

* To attempt to investigate the problem we repeated the experiment while measuring more data. In particular we measured the time from partial encoded chunk distribution to the verification of those parts on the receiving node, as well as the total data transfer rate from peers in the network. The plots of these are shown below. Notably the chunk distribution time seems to increase discontinuously at 20 shards, indicating some bottleneck suddenly takes over when there are many shards. Additionally, the data transfer rate is not monotonic, which suggests this bottleneck could be computational in nature (i.e. there is less data being sent over the network even though there are more chunks to send because the nodes are spending more time on creating and/or processing those chunks).

![chunk_distribution_time](https://user-images.githubusercontent.com/13788876/97621428-46c81180-19f9-11eb-9188-6da9ae1c9605.png)
![data_transfer_rate](https://user-images.githubusercontent.com/13788876/97621452-4c255c00-19f9-11eb-8967-446c2b2d544f.png)

For now, work has shifted to focus on measuring characteristics of networks with fewer shards (https://github.com/near/nearcore/issues/3530), so I am closing this issue for this cycle. A new issue can be created when we pick up the work again in a future cycle.

**Closed by birchmd** 2020-10-29 19:14 UTC
Labels: chain
