### ISSUE TITLE
RPC for querying receipts

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearcore#3177] opened 2020-08-16 04:45 UTC
Getting timeout errors while fetching tx-status of the receipt when using a single node setup on localhost.

```
$ near tx-status test.near:ADFm3ULGtbFycZzQXaTXogb2qDbAtW6CEtW7SgkJaHEm
Error:  TypedError: [-32000] Server error: Timeout error
    at JsonRpcProvider.sendJsonRpc (/usr/local/lib/node_modules/near-shell/node_modules/near-api-js/lib/providers/json-rpc-provider.js:157:27)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async /usr/local/lib/node_modules/near-shell/commands/tx-status.js:33:24
    at async Object.handler (/usr/local/lib/node_modules/near-shell/utils/exit-on-error.js:37:9) {
  type: 'UntypedError'
}
```

# Steps to reproduce

1. Send some transaction that has receipts (function calls / transfers)
2. Find the receipt ID
3. Call `near tx-status <account_id>:<receipt_hash>`

Observe timeout error.

Expected:
 - Either "not found" error
 - Or receipt info

**Comment by bowenwang1996** [comment] 2020-08-16 20:16
We disabled receipt query long ago. The issue here is that a node cannot distinguish just from the hash whether you intend to query transaction or receipt and it assumes that you are trying to query a transaction.

**Comment by frol** [comment] 2020-08-24 16:28
Should this be transformed into an issue of adding an API for fetching Receipt status (execution outcome)?

**Comment by bowenwang1996** [comment] 2020-11-21 19:19
According to @abacabadabacaba, it is now needed for the bridge to work. Let's prioritize this

**Comment by frol** [comment] 2020-11-21 21:04
What data is needed? Receipt or execution outcome, or both?

**Comment by bowenwang1996** [comment] 2020-11-23 15:49
@abacabadabacaba please clarify.

**Comment by abacabadabacaba** [comment] 2020-12-10 16:56
For the bridge, the receipt itself is needed (specifically, which functions were called, as well as the arguments).

**Comment by djsatok** [comment] 2020-12-11 10:23
@Kouprin , is this something that needs to be done to enable #3658 ? You managed to do it somehow, don't you?

The background is outlined in the https://github.com/near/rainbow-bridge/issues/432 . In short here're the steps that we would like to reproduce:

1. A user sends a [transaction](https://github.com/near/rainbow-token-connector/blob/da5828aa7008a917c2f9e7bcc46d9b50fbb61f7b/bridge-token/src/lib.rs#L55-L65) to token connector on NEAR. This transaction produces [execution outcome](https://github.com/near/rainbow-token-connector/blob/da5828aa7008a917c2f9e7bcc46d9b50fbb61f7b/bridge-token-factory/src/lib.rs#L206-L230).
2. This execution outcome is requested from NEAR in a provable format, ...
3. To [send it to Ethereum contract](https://github.com/near/rainbow-token-connector/blob/da5828aa7008a917c2f9e7bcc46d9b50fbb61f7b/erc20-connector/contracts/ERC20Locker.sol#L43-L48) to get tokens on Ethereum side.

Now, there should be an ability to do the step 2, having all the necessary info from the first transaction.

@Kouprin , can you please comment whether this is something that can be achieved at the moment?

**Comment by bowenwang1996** [comment] 2020-12-11 16:15
> Now, there should be an ability to do the step 2, having all the necessary info from the first transaction.

That is already possible currently. `EXPERIMENTAL_tx_status` endpoint allows one to query execution outcomes and will return all the receipts the transaction generated.

**Comment by frol** [comment] 2021-01-29 08:35
@khorolets we need a new `EXPERIMENTAL_receipt` method exposing Receipt info by a given Receipt ID (and chances are that we need to require Receiver Account ID due to sharding)

**Comment by khorolets** [comment] 2021-02-04 15:19
I forgot to refer to this issue in #3883 I guess we can close the issue.

**Closed** 2021-02-04 15:52 UTC
Labels: RPC, bug
