### ISSUE TITLE
Mocknet testing for stateful-to-stateless protocol upgrade

### ISSUE THREAD

**Issue by tayfunelmas** [near/nearcore#11465] opened 2024-06-03 22:08 UTC
Also see [the related task](https://github.com/near/near-one-project-tracking/issues/65) for preparing for the stateful-to-stateless transition.

This could be combined with the task [here about testing with 100+ nodes](https://github.com/near/nearcore/issues/11231).

**Comment by walnut-the-cat** [comment] 2024-06-25 19:37
duplicate of https://github.com/near/near-one-project-tracking/issues/65

**Closed** 2024-06-25 19:37 UTC
Labels: A-stateless-validation
