### ISSUE TITLE
Clock doesn't have unit ut

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5344] opened 2021-11-18 00:38 UTC
**Describe the bug**
Please provide a short description of the bug.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
- nearcore commit/branch
- rust version (if local)
- docker (if using docker)
- mainnet/testnet/betanet/local

**Additional context**

**Comment by mina86** [comment] 2021-11-18 01:45
Looks like mistakenly failed duplicate of https://github.com/near/nearcore/issues/5345

**Closed by mina86** 2021-11-18 01:45 UTC
