### ISSUE TITLE
Block height stopped at 23341948

### ISSUE THREAD

**Issue by lcgogo** [near/nearcore#3642] opened 2020-11-22 08:14 UTC
**Describe the bug**

Nov 22 08:11:52.266  WARN client: receive bad block: Invalid Chunk State
 Cause: Unknown
Nov 22 08:11:52.286  WARN client: receive bad block: Invalid Chunk State
 Cause: Unknown
Nov 22 08:11:53.619  INFO stats: #23341948 Downloading blocks 99%  17/14/40 peers ⬇ 140.5kiB/s ⬆ 3.0MiB/s 0.00 bps 0 gas/s CPU: 130%, Mem: 1.1 GiB
Nov 22 08:11:53.896  WARN client: receive bad block: Invalid Chunk State
 Cause: Unknown
Nov 22 08:11:53.923  WARN client: receive bad block: Invalid Chunk State
 Cause: Unknown
Nov 22 08:11:53.947  WARN client: receive bad block: Invalid Chunk State

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
- nearcore commit/branch 1.16.0 & 1.16.1
- rust version (if local)
- docker (if using docker)
- mainnet/testnet/betanet/local mainnet

**Additional context**

**Comment by snj33v** [comment] 2020-11-22 15:30
we are facing this too

**Comment by irisroyaltyf** [comment] 2020-11-22 15:35
have you solved this problem?

**Comment by lcgogo** [comment] 2020-11-23 04:42
> have you solved this problem?

not yet, have any idea?

**Comment by lcgogo** [comment] 2020-11-23 09:37
update to 1.16.2 and the log looks same. Use another server to resync one.

**Comment by frol** [comment] 2020-11-23 12:44
@lcgogo @irisroyaltyf you will, unfortunately, need to grab 1.16.2 release and do a resync. Did you run a `neard` build from master? What is your use-case? We also hit this problem internally running our Indexers and RosettaRPC nodes just because we did not follow the mainnet releases (needed more latest changes).

**Comment by frol** [comment] 2020-11-23 13:14
I have described the root cause of the problem in the issue #3645. Closing this as a "duplicate"

**Closed by frol** 2020-11-23 13:14 UTC

**Comment by lcgogo** [comment] 2020-11-24 08:03
@frol  Many thanks. got it. 
It is a little tricky that my 1.16.2 near node with old data of 1.16.2 catchup the latest height after 1 night running.
At the same time the resync near node is still stopped at height 9820210 with data folder increasing. I think it is still download snapshot.

**Comment by frol** [comment] 2020-11-28 08:26
@lcgogo full sync will take much longer than an incremental one (assuming archival node). How exactly the resync “stopped”? Is it “downloading headers”? In that case it is expected that it will report block height 9820210 (it is the genesis height)
