### ISSUE TITLE
staking_repro1.py with nightly_protocol failure

### ISSUE THREAD

**Issue by mikhailOK** [near/nearcore#4037] opened 2021-03-05 00:59 UTC
staking_repro1.py fails about half of the time
disabling `protocol_feature_forward_chunk_parts` makes it pass: http://nayduck.eastus.cloudapp.azure.com:3000/#/run/1240
failure example:http://nayduck.eastus.cloudapp.azure.com:3000/#/test/100505
node gets stuck: https://nayduckdiag.blob.core.windows.net/logs/100505_v2_test1
```
[2mMar 04 16:44:44.510[0m [34mDEBUG[0m chain: Head updated to 8zRKX1CjwuQn7YhjyxgsGcQfjPz9N2seabkKoDpZpa8j at 228    
[2mMar 04 16:44:44.511[0m [34mDEBUG[0m client: Block 8zRKX1CjwuQn7YhjyxgsGcQfjPz9N2seabkKoDpZpa8j was missing chunks but now is ready to be processed    
[2mMar 04 16:44:44.511[0m [34mDEBUG[0m chain: Block with missing chunks is accepted; me: Some("test1")    
[2mMar 04 16:44:44.511[0m [34mDEBUG[0m chain: Check orphans: from 8zRKX1CjwuQn7YhjyxgsGcQfjPz9N2seabkKoDpZpa8j, # orphans 0    
[2mMar 04 16:44:44.512[0m [34mDEBUG[0m client: Produce chunk: prev block is not caught up    
[2mMar 04 16:44:44.513[0m [31mERROR[0m client: Error producing chunk ChunkProducer("State for the epoch is not downloaded yet, skipping chunk production")    
[2mMar 04 16:44:44.518[0m [34mDEBUG[0m client: Catchup me: Some("test1"): sync_hash: `EJSLfpTw75LHTYLVXF99kDLFeM7Ce4xJN7jThYkZJFQ6`, sync_info: {0: ShardSyncDownload { downloads: [DownloadStatus { start_time: 2021-03-04T16:44:37.938883009Z, prev_update_time: 2021-03-04T16:44:37.938883009Z, run_me: false, error: false, done: true, state_requests_count: 1, last_target: Some(AccountId("test0")) }, DownloadStatus { start_time: 2021-03-04T16:44:37.938883009Z, prev_update_time: 2021-03-04T16:44:37.938883009Z, run_me: false, error: false, done: false, state_requests_count: 1, last_target: Some(PeerId(ed25519:Eo9W44tRMwcYcoua11yM7Xfr1DjgR4EWQFM3RU27MEX8)) }, DownloadStatus { start_time: 2021-03-04T16:44:37.938883009Z, prev_update_time: 2021-03-04T16:44:37.938883009Z, run_me: false, error: false, done: false, state_requests_count: 1, last_target: Some(PeerId(ed25519:Eo9W44tRMwcYcoua11yM7Xfr1DjgR4EWQFM3RU27MEX8)) }], status: StateDownloadParts }}    
```

**Comment by birchmd** [comment] 2021-03-05 16:22
@bowenwang1996 @mikhailOK Do you want me to look into this?

**Comment by bowenwang1996** [comment] 2021-03-05 17:17
@birchmd sure

**Comment by birchmd** [comment] 2021-03-05 21:36
Progress so far: eagerly sending chunk requests makes the test always pass ([commit](https://github.com/near/nearcore/commit/3423868) ; [Nayduck run](http://nayduck.eastus.cloudapp.azure.com:3000/#/run/1250))

The reason we were not sending the request right away before is because we assumed the chunk forward message would make most requests obsolete. I'll have to investigate further to see why this is not the case.

**Comment by birchmd** [comment] 2021-03-08 16:21
My hypothesis about what is going on here:

Chunk forwarding only sends chunks to validating nodes. In this test nodes come and go as validators (the whole point of the test seems to be to test staking an unstaking). In order for this test to run as quickly as it does I assume the epoch length must be quite short. So I think the issue has something to do with one node falling behind because it was not a validator and so got a chunk late, but the timing is such that it is near the end of an epoch (which happens frequently because epochs are short), and this causes a delay in block production going forward because that node should have become a validator again in the next epoch, which causes the test to time out (because there is a per-transaction timeout in addition to a complete test timeout).

That maybe isn't entirely accurate, but seems like it could be on the right track, and it explains the observation that eagerly sending chunk requests fixes the test. If this is the case then maybe the test can be fixed by making epochs longer and increasing the per-transaction timeout. Since this is a nightly test anyways, are there any objections to making this a longer test?

**Comment by bowenwang1996** [comment] 2021-03-08 18:02
Sure we can make epochs longer

**Comment by mikhailOK** [comment] 2021-03-08 18:49
From the log it looks like the node gets completely stuck
Node begins to download state here
```
[2mMar 04 16:44:37.655[0m [34mDEBUG[0m chain: Process block EJSLfpTw75LHTYLVXF99kDLFeM7Ce4xJN7jThYkZJFQ6 at 217, approvals: 1, me: Some("test1")    
[2mMar 04 16:44:37.656[0m [34mDEBUG[0m chain: Some("test1") Process block EJSLfpTw75LHTYLVXF99kDLFeM7Ce4xJN7jThYkZJFQ6, is_caught_up: false, need_to_start_fetching_state: true    
[2mMar 04 16:44:37.659[0m [34mDEBUG[0m chain: Header head updated to EJSLfpTw75LHTYLVXF99kDLFeM7Ce4xJN7jThYkZJFQ6 at 217    
[2mMar 04 16:44:37.664[0m [34mDEBUG[0m chain: Verifying challenges []    
[2mMar 04 16:44:37.665[0m [34mDEBUG[0m runtime: add validator proposals at block height 217 []    
[2mMar 04 16:44:37.666[0m [34mDEBUG[0m chain: Head updated to EJSLfpTw75LHTYLVXF99kDLFeM7Ce4xJN7jThYkZJFQ6 at 217    
[2mMar 04 16:44:37.668[0m [34mDEBUG[0m chain: Downloading state for block EJSLfpTw75LHTYLVXF99kDLFeM7Ce4xJN7jThYkZJFQ6    
[2mMar 04 16:44:37.668[0m [34mDEBUG[0m chain: Downloading state for [0], I'm Some("test1")    
[2mMar 04 16:44:37.669[0m [34mDEBUG[0m client: Block EJSLfpTw75LHTYLVXF99kDLFeM7Ce4xJN7jThYkZJFQ6 was missing chunks but now is ready to be processed    
```
And never manages to finish
```
[2mMar 04 16:45:09.207[0m [34mDEBUG[0m client: Catchup me: Some("test1"): sync_hash: `EJSLfpTw75LHTYLVXF99kDLFeM7Ce4xJN7jThYkZJFQ6`, sync_info: {0: ShardSyncDownload { downloads: [DownloadStatus { start_time: 2021-03-04T16:44:37.938883009Z, prev_update_time: 2021-03-04T16:44:37.938883009Z, run_me: false, error: false, done: true, state_requests_count: 1, last_target: Some(AccountId("test0")) }, DownloadStatus { start_time: 2021-03-04T16:44:37.938883009Z, prev_update_time: 2021-03-04T16:44:37.938883009Z, run_me: false, error: false, done: false, state_requests_count: 1, last_target: Some(PeerId(ed25519:Eo9W44tRMwcYcoua11yM7Xfr1DjgR4EWQFM3RU27MEX8)) }, DownloadStatus { start_time: 2021-03-04T16:44:37.938883009Z, prev_update_time: 2021-03-04T16:44:37.938883009Z, run_me: false, error: false, done: false, state_requests_count: 1, last_target: Some(PeerId(ed25519:Eo9W44tRMwcYcoua11yM7Xfr1DjgR4EWQFM3RU27MEX8)) }], status: StateDownloadParts }}    
```

There is potentially some interaction between missing chunks and catchup state sync

**Comment by birchmd** [comment] 2021-03-09 14:53
All tests with longer epochs passed ([commit ](https://github.com/near/nearcore/commit/09a7da2); [Nayduck](http://nayduck.eastus.cloudapp.azure.com:3000/#/run/1266))

So if there is an interaction between missing chunks and state sync, I think it must only happen across epoch boundaries.

@bowenwang1996 do you think we should try to look into this possible interaction more closely (a bug which can cause the node to get stuck forever is pretty serious), or because state sync is being re-designed anyways (I think this is the case), should we leave it for now since we know how to make the test pass?

**Comment by bowenwang1996** [comment] 2021-03-09 16:33
@birchmd Misha will look into this. @mikhailOK it is possible that this is caused by `state_sync_timeout` being too large. We can try to set it to a very small number and see if it helps.

**Closed** 2021-03-11 19:51 UTC
Labels: python test
