### ISSUE TITLE
sync_state_nodes::sync_empty_state is flaky

### ISSUE THREAD

**Issue by chefsale** [near/nearcore#4702] opened 2021-08-17 16:12 UTC
The test is often flaky on both stable and nightly tests:

Examples from PRs:
https://buildkite.com/nearprotocol/nearcore/builds/3315
https://buildkite.com/nearprotocol/nearcore/builds/3318

```
[2021-08-17T15:30:11Z] thread 'sync_state_nodes::sync_empty_state' panicked at 'Timed out waiting for the condition', chain/network/src/test_utils.rs:167:21
--
  | [2021-08-17T15:30:11Z] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  | [2021-08-17T15:30:11Z] thread 'sync_state_nodes::sync_empty_state' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Non-zero exit code: 1" }', /var/lib/buildkite-agent/builds/buildkite-i-012af86805ffd0f3e-1/nearprotocol/nearcore/test-utils/actix-test-utils/src/lib.rs:103:15
  | [2021-08-17T15:30:11Z]
  | [2021-08-17T15:30:11Z]
  | [2021-08-17T15:30:11Z] failures:
  | [2021-08-17T15:30:11Z]     sync_state_nodes::sync_empty_state
  | [2021-08-17T15:30:11Z]
  | [2021-08-17T15:30:11Z] test result: FAILED. 33 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1173.02s
```

cc: @bowenwang1996 please assign to the relevant person.

**Comment by bowenwang1996** [comment] 2021-08-18 00:07
Duplicate of #4036

**Closed by bowenwang1996** 2021-08-18 00:07 UTC
