### ISSUE TITLE
view contract state failed with unexpected errors on testnet

### ISSUE THREAD

**Issue by think-in-universe** [near/nearcore#4288] opened 2021-05-08 07:43 UTC
**Describe the bug**

Some unexpected failure when querying certain blocks with `near-api-js`.

Failed when querying contract state for some blocks with  `await account.viewState('p', blockId ? { blockId } : null);`  with **near-api-js** on testnet,  which call the RPC APIs https://docs.near.org/docs/api/rpc#view-contract-state    

**ERROR**:     
- `Error: [-32000] Server error: The node does not track the shard ID 0`
- `Error: [-32000] Server error: DB Not Found Error: BLOCK HEADER: 4HCZAnsbL49RcK9Vjx6Mvwj1R7k51jtHinNRiiANjx3K`

**To Reproduce**
To reproduce the failure, we could call RPC with HTTPie

**Query 1**: query the below block will return data successfully:

```bash
http post https://rpc.testnet.near.org jsonrpc=2.0 id=dontcare method=query \
  params:='{
    "request_type": "view_state",
    "account_id": "feiyu-dev.testnet",
    "prefix_base64": "cA==",
    "block_id": "CczTW3GrgUKie4iB5vHRjEodMYRKpaU6hD32BByx3mpz"
  }'
```

returned json data:

```json
{
    "id": "dontcare",
    "jsonrpc": "2.0",
    "result": {
        "block_hash": "CczTW3GrgUKie4iB5vHRjEodMYRKpaU6hD32BByx3mpz",
        "block_height": 46699063,
        "proof": [],
        "values": [
            {
                "key": "cAAAAAAAAAAA",
                "proof": [],
                "value": "HgAAAP8A/wACAAAAA1T2/CtlfBb///8AAAAAAAAAAAAAAAAA////AAAAAAAAAAAAAAAAAP///wAAAAAAAAAAAAAAAAD///8AAAAAAAAAAAAAAAAA////AAAAAAAAAAAAAAAAAP///wAAAAAAAAAAAAAAAAD///8AAAAAAAAAAAAAAAAA////AAAAAAAAAAAAAAAAAP///wAAAAAAAAAAAAAAAAAhISEACQAAALQCkCCRd3wW////AAAAAAAAAAAAAAAAAP///wAAAAAAAAAAAAAAAAD///8AAAAAAAAAAAAAAAAA////AAAAAAAAAAAAAAAAAP///wAAAAAAAAAAAAAAAAD///8AAAAAAAAAAAAAAAAA////AAAAAAAAAAAAAAAAAP///wAAAAAAAAAAAAAAAAD///8AAAAAAAAAAAAAAAAAISEhAAkAAACYsyAk1Kl8Fv///wAAAAAAAAAAAAAAAAD///8AAAAAAAAAAAAAAAAA////AAAAAAAAAAAAAAAAAP///wAAAAAAAAAAAAAAAAD///8AAAAAAAAAAAAAAAAA////AAAAAAAAAAAAAAAAAP///wAAAAAAAAAAAAAAAAD///8AAAAAAAAAAAAAAAAA////AAAAAAAAAAAAAAAAAA=="
            },
           ...
        ]
    }
}
```

**Query 2**: query the below block will return error `DB Not Found Error: BLOCK HEADER: 4HCZAnsbL49RcK9Vjx6Mvwj1R7k51jtHinNRiiANjx3K`

```bash
http post https://rpc.testnet.near.org jsonrpc=2.0 id=dontcare method=query \
  params:='{
    "request_type": "view_state",
    "account_id": "feiyu-dev.testnet",
    "prefix_base64": "cA==",
    "block_id": "4HCZAnsbL49RcK9Vjx6Mvwj1R7k51jtHinNRiiANjx3K"
  }'
```

**Query 3**: query the below block will return error `The node does not track the shard ID 0`

```bash
http post https://rpc.testnet.near.org jsonrpc=2.0 id=dontcare method=query \
  params:='{
    "request_type": "view_state",
    "account_id": "feiyu-dev.testnet",
    "prefix_base64": "cA==",
    "block_id": "3iitgu7mM5JpeCjAQQAWLc2emZmghB392NzrSyMLFwDM"
  }'
```

**Expected behavior**
For Query 2 and 3, the query should return JSON data correctly. 

**Version (please complete the following information):**
- tested on the latest testnet version

**Additional context**
The failure may be related to the recent testnet issue: https://discord.com/channels/490367152054992913/611591221474885632/839833836077580331

**Comment by bowenwang1996** [comment] 2021-05-08 15:46
@chefsale @mhalambek looks like there might be some config issue when you did the update. All nodes behind the load balancer should track the shard.

**Comment by think-in-universe** [comment] 2021-05-10 15:45
is this something we can fix in short term?  one partner project is impacted / blocked by this issue.

**Comment by chefsale** [comment] 2021-05-10 23:52
So, I looked into this. I thought this would be expected behaviour as the blocks begin queried are older than five epochs, but I tried the same queries on archival nodes and got the same results. It works on newer blocks thought normally.
```
http post https://archival-rpc.testnet.near.org jsonrpc=2.0 id=dontcare method=query \
                                                                  params:='{
                                                                    "request_type": "view_state",
                                                                    "account_id": "feiyu-dev.testnet",
                                                                    "prefix_base64": "cA==",
                                                                    "block_id": "3JbLTrLsTyC9svSaE6VEfKfrE6CVrkXfBkyk4p5qvQPN"
                                                                  }'
HTTP/1.1 200 OK
Alt-Svc: clear
Via: 1.1 google
content-length: 20940
content-type: application/json
date: Mon, 10 May 2021 23:44:37 GMT

{
    "id": "dontcare",
    "jsonrpc": "2.0",
    "result": {
        "block_hash": "3JbLTrLsTyC9svSaE6VEfKfrE6CVrkXfBkyk4p5qvQPN",
        "block_height": 47169177,
        "proof": [],
        "values": [
            {
                "key": "cAAAAAAAAAAA",
                "proof": [],
...
```

I checked and the nodes seem to be properly configured (tracking shards/archival)

It could be likely that there is some bug which happened during the RPC refactor, but hard to say I will take a bit deeper look tomorrow.

**Comment by chefsale** [comment] 2021-05-10 23:54
And query 2 doesn't work as they are querying a transaction instead of a block: https://explorer.testnet.near.org/transactions/4HCZAnsbL49RcK9Vjx6Mvwj1R7k51jtHinNRiiANjx3K

**Comment by bowenwang1996** [comment] 2021-05-11 00:27
@think-in-universe they should run their own archival node or indexer if they want to query old data.

**Comment by think-in-universe** [comment] 2021-05-11 08:00
thanks Sandi @chefsale 

yeah. Query 2 is a transaction actually, so it's not an issue I think. 

The ERROR `The node does not track the shard ID 0` still happens quite frequently.

**Comment by frol** [comment] 2021-05-20 20:33
It seems that this is resolved now. At least, I cannot reproduce it.

@chefsale @mhalambek The error "the node does not track the shard ID 0" suggested that we had archival node misconfiguration which did not track the shard 0. Was/is it the case? Can you try querying all the archival nodes we run by IP address directly using the suggested query to identify the misbehaving node?

**Comment by chefsale** [comment] 2021-05-20 22:05
Yes, one node of all had the config wrong. This was an old legacy node and once that node got hit ir was thrown. We can close the issue.

**Closed by chefsale** 2021-05-20 22:05 UTC
