### ISSUE TITLE
1.31.0-rc.1 - SIGTERM bug 

### ISSUE THREAD

**Issue by nick-u410** [near/nearcore#8293] opened 2023-01-05 20:23 UTC
Saw this while upgrading testnet to 1.31.0-rc.1 The node restarted and recovered. It says "bug detected", so letting the team know about it. 
```
2023-01-04T17:06:45.517603Z  INFO neard: version="1.31.0-rc.1" build="1.31.0-rc.1" latest_protocol=57
2023-01-04T17:08:37.275282Z  INFO stats: #111558947 Downloading blocks 52.59% (339 left; at 111558947) 24 peers ⬇ 4.08 MB/s ⬆ 2.82 MB/s 12.11 bps 111 Tgas/s CPU: 279%, Mem: 2.16 GB
2023-01-04T17:08:38.339374Z  WARN neard: SIGTERM, stopping... this may take a few minutes.
thread '<unnamed>' panicked at 'bug detected: OutboundHandshakePermit dropped before calling Pool.insert_ready()', chain/network/src/peer_manager/connection/mod.rs:323:25
2023-01-04T17:08:38.344593Z  INFO neard: Waiting for RocksDB to gracefully shutdown
2023-01-04T17:08:38.344602Z  INFO db: Waiting for remaining RocksDB instances to shut down num_instances=1
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: near_network::peer_manager::connection::Pool::insert_ready
   3: tokio::runtime::task::harness::poll_future
   4: tokio::runtime::task::raw::poll
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

when I first deployed the upgrade, I got an error message saying my ulimit was too low and it needed to be updated to 65535. I did that and restarted the node and then I got the above message. 

I also run 2 other nodes, I applied the ulimit changes to those first and never saw the panic above.

**Comment by paulmattei** [comment] 2023-02-24 09:50
We keep getting these errors. Any idea what causes it?

https://gist.github.com/paulmattei/c4e6b8de51aab9804462dbe70c57129c

**Comment by akhi3030** [comment] 2023-02-24 10:01
CC: @walnut-the-cat.  There doesn't seem to have been any movement on this for some time.

**Comment by pompon0** [comment] 2023-02-24 10:09
This is a race condition caused by unpredictability of Actix. It shouldn't have caused any harm, but thank you for reporting it anyway. I'll fix it today.

**Comment by paulmattei** [comment] 2023-02-24 10:18
> This is a race condition caused by unpredictability of Actix. It shouldn't have caused any harm, but thank you for reporting it anyway. I'll fix it today.

Thanks. Once we hit it we then crash loop, so there is harm in the sense that this node now will not sync. We see this on testnet with 31.1 and 31-rc4 and mainnet with 31.1

**Comment by pompon0** [comment] 2023-02-24 10:53
In both examples that you have provided, there is a log line before the OutboundHandshakePermit panic.
```
2023-01-04T17:08:38.339374Z  WARN neard: SIGTERM, stopping... this may take a few minutes.
```
which means that the process was shutting down even before the panic happened.
In your second example there was an earlier panic:
```
 thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /build/neard-1.31.0-rc.4-vendor.tar.gz/rkyv/src/collections/btree_map/mod.rs:657:31
```
which suggests that a different bug was the reason.

**Comment by pompon0** [comment] 2023-02-24 10:54
@akhi3030 perhaps this is rather a runtime-related bug then?

**Comment by akhi3030** [comment] 2023-02-24 11:16
Thanks for the investigations @pompon0!  CC: @Ekleog-NEAR, could you take a look then please?

**Comment by pompon0** [comment] 2023-02-24 12:58
I've removed the link to https://github.com/near/nearcore/pull/8639 , so that it doesn't close the issue.

**Comment by akhi3030** [comment] 2023-02-24 13:16
Ekleog-NEAR is not available to work on this.  @jakmeier: could you take a look please?

**Comment by paulmattei** [comment] 2023-02-24 13:17
In case helpful - you can actually completely replicate the environment in which we see these errors : https://docs.google.com/document/d/1tjIXrrjDa9xWT7brt5lRW4aysbe_Fp5IXtcvR1pPu38/edit

**Comment by jakmeier** [comment] 2023-02-27 16:34
@paulmattei Thanks for the gist and doc!

This might sound weird, but can you try compiling with Rust <= 1.66.1?

The automated setup seems to install the latest stable Rust version (Rust 1.67.1 as of today) and we know about some issues upstream in rkyv that breaks a few things when the new struct optimzations of Rust 1.67 are applied. Based on your backtrace, the issue looks suspiciously similar. (https://github.com/rkyv/rkyv/issues/338)

Not quite sure if we really have to but we might need a 1.31.2 release to make neard work when compiled with Rust 1.67. If you could confirm that this really is the issue, it would be helpful for us to decide on next steps.

**Comment by kucharskim** [comment] 2023-02-27 16:41
> This might sound weird, but can you try compiling with Rust <= 1.66.1?

How do you force specific Rust version?

**Comment by jakmeier** [comment] 2023-02-27 16:47
If rustup is already installed, this should work:

Install the older toolchain
```
rustup install 1.66.1
```

In the nearcore directory, override the default toolchian
```
rustup override set 1.66.1
```

Now you can recompile (`make release`) and your new `./target/release/neard` will be updated.

**Comment by nagisa** [comment] 2023-02-27 19:34
I fear that on this specific machine, the rocksdb database column that holds the cache of contract artifacts may be malformed with no _easy_ way out. We unfortunately do not have a command that would allow one to drop (and regenerate) this state (I filed https://github.com/near/nearcore/issues/8650.) The other way to do so is to run a binary with [this line](https://github.com/near/nearcore/blob/67032e58f3412a80089bde9be8924bf22eb327a1/runtime/near-vm-runner/src/wasmer2_runner.rs#L236) patched to a different number. Not that it would make for a great experience. I think the most reasonable way forward is going to be to restore the entire state to a known-working state (e.g. snapshots, backups, copying it over from another node, etc…)

That said, in the future please consider the version in `rust-toolchain` to be a requirement, not a recommendation. Our deployment and considerations largely assume `rustup`, and while we strive to write code that is not dependent on the toolchain version, sometimes oversights like the one with `rkyv` do happen. We did apply the necessary steps to mitigate the issue and fixed the issue for good, but deployment of these fixes assume `rust-toolchain` is honoured.

**Comment by paulmattei** [comment] 2023-02-28 15:15
> I fear that on this specific machine, the rocksdb database column that holds the cache of contract artifacts may be malformed with no _easy_ way out. We unfortunately do not have a command that would allow one to drop (and regenerate) this state (I filed #8650.) The other way to do so is to run a binary with [this line](https://github.com/near/nearcore/blob/67032e58f3412a80089bde9be8924bf22eb327a1/runtime/near-vm-runner/src/wasmer2_runner.rs#L236) patched to a different number. Not that it would make for a great experience. I think the most reasonable way forward is going to be to restore the entire state to a known-working state (e.g. snapshots, backups, copying it over from another node, etc…)
> 
> That said, if you're compiling neard yourself, please consider the version in `rust-toolchain.toml` to be a requirement, not a recommendation. Our deployment and considerations largely assume `rustup`, and while we strive to write code that is not dependent on the toolchain version, sometimes oversights like the one with `rkyv` do happen. We did apply the necessary steps to mitigate the issue and fixed the issue for good, but deployment of these fixes assume `rust-toolchain.toml` is honoured.

Yes - this fixed it for us. https://github.com/kuutamolabs/near-staking-knd/pull/551 We'll follow the version in the toolchain moving forward. Thank you!

**Comment by akhi3030** [comment] 2023-03-07 13:05
Looks like all work here is done.  Please comment and reopen if further investigation is required.

**Closed by akhi3030** 2023-03-07 13:05 UTC
Labels: T-contract-runtime
