### ISSUE TITLE
Consider moving store validator to be a subcomand of neard

### ISSUE THREAD

**Issue by matklad** [near/nearcore#6957] opened 2022-06-03 10:41 UTC
Essentially, all motivations from https://github.com/near/nearcore/issues/5193 apply to store validator as well I think?

**Comment by mina86** [comment] 2022-06-03 13:37
This looks like a duplicate of https://github.com/near/nearcore/issues/6705

**Comment by matklad** [comment] 2022-06-03 13:48
That's slightly diffrent, but yeah, makes sense to kill both with one PR.

**Closed** 2022-06-03 13:48 UTC
Labels: C-housekeeping, T-node
