### ISSUE TITLE
Separate EpochManager away from Runtime

### ISSUE THREAD

**Issue by mzhangmzz** [near/nearcore#4715] opened 2021-08-19 20:20 UTC
Currently, `EpochManager` is part of `Runtime` and other structs such as `Client` need to access epoch information through the runtime interface. However, runtime should not care anything about epoch or shard at all. It should simply do one thing, take some transactions and receipts and apply that to the state. 

`EpochManager` is also accessed through runtime by a `RwLock`. That is unnecessary and complicates the code a lot, and introduces bugs that cannot be checked by the compiler. We can get rid of the lock if we can move `EpochManager` outside of runtime, if we guarantee that it is only used by the client_actor thread.

**Comment by bowenwang1996** [comment] 2021-08-19 22:47
Duplicate of #2745. Basically we need to decide whether we want to make epoch manager a smart contract.

**Closed by bowenwang1996** 2021-08-19 22:47 UTC
Labels: A-transaction-runtime
