### ISSUE TITLE
Expand GCS-based State Sync to allow Decentralised transfer of parts

### ISSUE THREAD

**Issue by gmilescu** [near/nearcore#9731] opened 2023-07-31 10:01 UTC
<i>[ND-566] created by None</i>

[ND-566]: https://pagodaplatform.atlassian.net/browse/ND-566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by telezhnaya** [comment] 2023-12-11 16:04
duplicate of https://github.com/near/nearcore/issues/9575

**Closed by telezhnaya** 2023-12-11 16:04 UTC
Labels: Epic, Node, milestone-2023-08
