### ISSUE TITLE
Random test failure `routing::archival_node`

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5368] opened 2021-11-18 22:24 UTC
I've seen a random test failure for `routing::archival_node`
```


[2021-11-18T19:36:58Z] test routing::archival_node ... FAILED
--
  | [2021-11-18T19:36:58Z]
  | [2021-11-18T19:36:58Z] failures:
  | [2021-11-18T19:36:58Z]
  | [2021-11-18T19:36:58Z] ---- routing::archival_node stdout ----
  | [2021-11-18T19:36:58Z] BBBB Slept 15001; max_wait_ms 15000
  | [2021-11-18T19:36:58Z] thread 'routing::archival_node' panicked at 'Timed out waiting for the condition', chain/network/src/test_utils.rs:153:21
  | [2021-11-18T19:36:58Z] stack backtrace:
  | [2021-11-18T19:36:58Z]    0: rust_begin_unwind
  | [2021-11-18T19:36:58Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5
  | [2021-11-18T19:36:58Z]    1: core::panicking::panic_fmt
  | [2021-11-18T19:36:58Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:101:14
  | [2021-11-18T19:36:58Z]    2: near_network::test_utils::WaitOrTimeoutActor::wait_or_timeout::{{closure}}
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/builds/buildkite-i-032c9710e35bd8ba1-1/nearprotocol/nearcore/chain/network/src/test_utils.rs:153:21
  | [2021-11-18T19:36:58Z]    3: <F as actix::utils::TimerFuncBox<A>>::call
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.11.0-beta.2/src/utils.rs:117:9
  | [2021-11-18T19:36:58Z]    4: <actix::utils::TimerFunc<A> as actix::fut::ActorFuture>::poll
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.11.0-beta.2/src/utils.rs:138:21
  | [2021-11-18T19:36:58Z]    5: <core::pin::Pin<P> as actix::fut::ActorFuture>::poll
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.11.0-beta.2/src/fut/mod.rs:323:9
  | [2021-11-18T19:36:58Z]    6: <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.11.0-beta.2/src/contextimpl.rs:384:23
  | [2021-11-18T19:36:58Z]    7: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/core.rs:161:17
  | [2021-11-18T19:36:58Z]    8: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/loom/std/unsafe_cell.rs:14:9
  | [2021-11-18T19:36:58Z]    9: tokio::runtime::task::core::CoreStage<T>::poll
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/core.rs:151:13
  | [2021-11-18T19:36:58Z]   10: tokio::runtime::task::harness::poll_future::{{closure}}
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:461:19
  | [2021-11-18T19:36:58Z]   11: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  | [2021-11-18T19:36:58Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panic/unwind_safe.rs:271:9
  | [2021-11-18T19:36:58Z]   12: std::panicking::try::do_call
  | [2021-11-18T19:36:58Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:403:40
  | [2021-11-18T19:36:58Z]   13: __rust_try
  | [2021-11-18T19:36:58Z]   14: std::panicking::try
  | [2021-11-18T19:36:58Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:367:19
  | [2021-11-18T19:36:58Z]   15: std::panic::catch_unwind
  | [2021-11-18T19:36:58Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panic.rs:129:14
  | [2021-11-18T19:36:58Z]   16: tokio::runtime::task::harness::poll_future
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:449:18
  | [2021-11-18T19:36:58Z]   17: tokio::runtime::task::harness::Harness<T,S>::poll_inner
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:98:27
  | [2021-11-18T19:36:58Z]   18: tokio::runtime::task::harness::Harness<T,S>::poll
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:53:15
  | [2021-11-18T19:36:58Z]   19: tokio::runtime::task::raw::poll
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/raw.rs:113:5
  | [2021-11-18T19:36:58Z]   20: tokio::runtime::task::raw::RawTask::poll
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/raw.rs:70:18
  | [2021-11-18T19:36:58Z]   21: tokio::runtime::task::LocalNotified<S>::run
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/mod.rs:343:9
  | [2021-11-18T19:36:58Z]   22: tokio::task::local::LocalSet::tick::{{closure}}
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/task/local.rs:521:54
  | [2021-11-18T19:36:58Z]   23: tokio::coop::with_budget::{{closure}}
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:106:9
  | [2021-11-18T19:36:58Z]   24: std::thread::local::LocalKey<T>::try_with
  | [2021-11-18T19:36:58Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/thread/local.rs:399:16
  | [2021-11-18T19:36:58Z]   25: std::thread::local::LocalKey<T>::with
  | [2021-11-18T19:36:58Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/thread/local.rs:375:9
  | [2021-11-18T19:36:58Z]   26: tokio::coop::with_budget
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:99:5
  | [2021-11-18T19:36:58Z]   27: tokio::coop::budget
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:76:5
  | [2021-11-18T19:36:58Z]   28: tokio::task::local::LocalSet::tick
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/task/local.rs:521:31
  | [2021-11-18T19:36:58Z]   29: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/task/local.rs:646:16
  | [2021-11-18T19:36:58Z]   30: tokio::macros::scoped_tls::ScopedKey<T>::set
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/macros/scoped_tls.rs:61:9
  | [2021-11-18T19:36:58Z]   31: tokio::task::local::LocalSet::with
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/task/local.rs:559:9
  | [2021-11-18T19:36:58Z]   32: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/task/local.rs:632:9
  | [2021-11-18T19:36:58Z]   33: tokio::task::local::LocalSet::run_until::{{closure}}
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/task/local.rs:505:9
  | [2021-11-18T19:36:58Z]   34: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  | [2021-11-18T19:36:58Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/future/mod.rs:80:19
  | [2021-11-18T19:36:58Z]   35: <core::pin::Pin<P> as core::future::future::Future>::poll
  | [2021-11-18T19:36:58Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/future/future.rs:119:9
  | [2021-11-18T19:36:58Z]   36: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::{{closure}}
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:230:62
  | [2021-11-18T19:36:58Z]   37: tokio::coop::with_budget::{{closure}}
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:106:9
  | [2021-11-18T19:36:58Z]   38: std::thread::local::LocalKey<T>::try_with
  | [2021-11-18T19:36:58Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/thread/local.rs:399:16
  | [2021-11-18T19:36:58Z]   39: std::thread::local::LocalKey<T>::with
  | [2021-11-18T19:36:58Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/thread/local.rs:375:9
  | [2021-11-18T19:36:58Z]   40: tokio::coop::with_budget
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:99:5
  | [2021-11-18T19:36:58Z]   41: tokio::coop::budget
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:76:5
  | [2021-11-18T19:36:58Z]   42: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:230:39
  | [2021-11-18T19:36:58Z]   43: tokio::runtime::basic_scheduler::enter::{{closure}}
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:339:29
  | [2021-11-18T19:36:58Z]   44: tokio::macros::scoped_tls::ScopedKey<T>::set
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/macros/scoped_tls.rs:61:9
  | [2021-11-18T19:36:58Z]   45: tokio::runtime::basic_scheduler::enter
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:339:5
  | [2021-11-18T19:36:58Z]   46: tokio::runtime::basic_scheduler::Inner<P>::block_on
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:218:9
  | [2021-11-18T19:36:58Z]   47: tokio::runtime::basic_scheduler::InnerGuard<P>::block_on
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:489:9
  | [2021-11-18T19:36:58Z]   48: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:178:24
  | [2021-11-18T19:36:58Z]   49: tokio::runtime::Runtime::block_on
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/mod.rs:461:46
  | [2021-11-18T19:36:58Z]   50: tokio::task::local::LocalSet::block_on
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/task/local.rs:466:9
  | [2021-11-18T19:36:58Z]   51: actix_rt::runtime::Runtime::block_on
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-2.3.0/src/runtime.rs:80:9
  | [2021-11-18T19:36:58Z]   52: actix_rt::system::SystemRunner::run
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-2.3.0/src/system.rs:167:15
  | [2021-11-18T19:36:58Z]   53: near_actix_test_utils::run_actix
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/builds/buildkite-i-032c9710e35bd8ba1-1/nearprotocol/nearcore/test-utils/actix-test-utils/src/lib.rs:103:5
  | [2021-11-18T19:36:58Z]   54: network::runner::start_test
  | [2021-11-18T19:36:58Z]              at ./tests/network/runner.rs:679:5
  | [2021-11-18T19:36:58Z]   55: network::routing::archival_node
  | [2021-11-18T19:36:58Z]              at ./tests/network/routing.rs:284:5
  | [2021-11-18T19:36:58Z]   56: network::routing::archival_node::{{closure}}
  | [2021-11-18T19:36:58Z]              at ./tests/network/routing.rs:259:1
  | [2021-11-18T19:36:58Z]   57: core::ops::function::FnOnce::call_once
  | [2021-11-18T19:36:58Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:227:5
  | [2021-11-18T19:36:58Z]   58: core::ops::function::FnOnce::call_once
  | [2021-11-18T19:36:58Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:227:5
  | [2021-11-18T19:36:58Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  | [2021-11-18T19:36:58Z] thread 'routing::archival_node' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Non-zero exit code: 1" }', /var/lib/buildkite-agent/builds/buildkite-i-032c9710e35bd8ba1-1/nearprotocol/nearcore/test-utils/actix-test-utils/src/lib.rs:103:15
  | [2021-11-18T19:36:58Z] stack backtrace:
  | [2021-11-18T19:36:58Z]    0: rust_begin_unwind
  | [2021-11-18T19:36:58Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5
  | [2021-11-18T19:36:58Z]    1: core::panicking::panic_fmt
  | [2021-11-18T19:36:58Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:101:14
  | [2021-11-18T19:36:58Z]    2: core::result::unwrap_failed
  | [2021-11-18T19:36:58Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/result.rs:1617:5
  | [2021-11-18T19:36:58Z]    3: core::result::Result<T,E>::unwrap
  | [2021-11-18T19:36:58Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/result.rs:1299:23
  | [2021-11-18T19:36:58Z]    4: near_actix_test_utils::run_actix
  | [2021-11-18T19:36:58Z]              at /var/lib/buildkite-agent/builds/buildkite-i-032c9710e35bd8ba1-1/nearprotocol/nearcore/test-utils/actix-test-utils/src/lib.rs:103:5
  | [2021-11-18T19:36:58Z]    5: network::runner::start_test
  | [2021-11-18T19:36:58Z]              at ./tests/network/runner.rs:679:5
  | [2021-11-18T19:36:58Z]    6: network::routing::archival_node
  | [2021-11-18T19:36:58Z]              at ./tests/network/routing.rs:284:5
  | [2021-11-18T19:36:58Z]    7: network::routing::archival_node::{{closure}}
  | [2021-11-18T19:36:58Z]              at ./tests/network/routing.rs:259:1
  | [2021-11-18T19:36:58Z]    8: core::ops::function::FnOnce::call_once
  | [2021-11-18T19:36:58Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:227:5
  | [2021-11-18T19:36:58Z]    9: core::ops::function::FnOnce::call_once
  | [2021-11-18T19:36:58Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:227:5
  | [2021-11-18T19:36:58Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  | [2021-11-18T19:36:58Z]
  | [2021-11-18T19:36:58Z]
  | [2021-11-18T19:36:58Z] failures:
  | [2021-11-18T19:36:58Z]     routing::archival_node
  | [2021-11-18T19:36:58Z]
  | [2021-11-18T19:36:58Z] test result: FAILED. 28 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out; finished in 34.28s
  | [2021-11-18T19:36:58Z]
  | [2021-11-18T19:36:58Z] error: test failed, to rerun pass '-p integration-tests --test network'
  | [2021-11-18T19:36:58Z] 🚨 Error: The command exited with status 101


```

https://buildkite.com/nearprotocol/nearcore/builds/7514#4daa7b02-cc4c-4479-b53e-b4b7fc633d32

That's a test for `networking` so I'll be most likely fixing it.
Adding issue not to forget.

**Comment by bowenwang1996** [comment] 2021-11-18 23:06
Duplicate of https://github.com/near/nearcore/issues/5357. Please check whether an issue is already created before you create one

**Closed by bowenwang1996** 2021-11-18 23:06 UTC
