### ISSUE TITLE
my node not work

### ISSUE THREAD

**Issue by wangtao19911111** [near/nearcore#6040] opened 2022-01-11 06:37 UTC
Jan 11 06:18:05.443  WARN sync: Sync: ban a fraudulent peer: ed25519:92QLB3omymQ773ZFZZboQFFQKVm1j9cQDNi2iJiq2FKq@34.150.250.39:24567, claimed height: 57158728    
Jan 11 06:18:05.443  WARN network: Banning peer Some(ed25519:92QLB3omymQ773ZFZZboQFFQKVm1j9cQDNi2iJiq2FKq@34.150.250.39:24567) for HeightFraud
Jan 11 06:18:05.443  WARN network: Banning peer ed25519:92QLB3omymQ773ZFZZboQFFQKVm1j9cQDNi2iJiq2FKq for HeightFraud
Jan 11 06:18:10.226  INFO stats: #55243952 Downloading headers 95.96% (1914776)   7/1/40 peers ⬇ 0.9kiB/s ⬆ 0.1kiB/s 0.00 bps 0 gas/s CPU: 1%, Mem: 191.9 MiB    
Jan 11 06:18:20.230  INFO stats: #55243952 Downloading headers 95.96% (1914724)   7/1/40 peers ⬇ 0.9kiB/s ⬆ 0.1kiB/s 0.00 bps 0 gas/s CPU: 1%, Mem: 192.3 MiB    
Jan 11 06:18:25.453  WARN sync: Sync: ban a fraudulent peer: ed25519:HrjrfCN1d3QhuUoPd2zfYns1hg2JHnVj1u5ZWeK6BUSh@34.102.20.169:24567, claimed height: 57158676    
Jan 11 06:18:26.177  WARN network: Banning peer Some(ed25519:HrjrfCN1d3QhuUoPd2zfYns1hg2JHnVj1u5ZWeK6BUSh@34.102.20.169:24567) for HeightFraud
Jan 11 06:18:26.177  WARN network: Banning peer ed25519:HrjrfCN1d3QhuUoPd2zfYns1hg2JHnVj1u5ZWeK6BUSh for HeightFraud
Jan 11 06:18:30.232  INFO stats: #55243952 Downloading headers 95.96% (1914724)   6/1/40 peers ⬇ 0.7kiB/s ⬆ 0.1kiB/s 0.00 bps 0 gas/s CPU: 1%, Mem: 192.4 MiB    
Jan 11 06:18:39.373  WARN network: Attempting to connect to a node (ed25519:53CoarKdkvQdnvYTqs1bqsuNrmA8oz72oc6wVLeGctnJ@0.0.0.0:24567) with a different genesis block. Our genesis: GenesisId { chain_id: "mainnet", hash: `EPnLgE7iEq9s7yTkos96M3cWymH5avBAPm3qx3NXqR8H` }, their genesis: GenesisId { chain_id: "testnet", hash: `FWJ9kR6KFWoyMoNjpLXXGHeuiy7tEY6GmoFeCA5yuc6b` }
Jan 11 06:18:40.236  INFO stats: #55243952 Downloading headers 95.96% (1914707)   6/1/40 peers ⬇ 0.7kiB/s ⬆ 0.1kiB/s 0.00 bps 0 gas/s CPU: 1%, Mem: 192.5 MiB    
Jan 11 06:18:45.458  WARN sync: Sync: ban a fraudulent peer: ed25519:E3NGxdgU69WvyjfM85fDChBcLxVgKdxPGEhU3HxoPyp4@34.91.254.76:24567, claimed height: 57158659    
Jan 11 06:18:45.458  WARN network: Banning peer Some(ed25519:E3NGxdgU69WvyjfM85fDChBcLxVgKdxPGEhU3HxoPyp4@34.91.254.76:24567) for HeightFraud
Jan 11 06:18:45.458  WARN network: Banning peer ed25519:E3NGxdgU69WvyjfM85fDChBcLxVgKdxPGEhU3HxoPyp4 for HeightFraud
Jan 11 06:18:50.238  INFO stats: #55243952 Downloading headers 95.96% (1914707)   5/2/40 peers ⬇ 0.5kiB/s ⬆ 70 B/s 0.00 bps 0 gas/s CPU: 1%, Mem: 190.6 MiB    
Jan 11 06:19:00.240  INFO stats: #55243952 Downloading headers 95.96% (1914694)   5/2/40 peers ⬇ 0.5kiB/s ⬆ 80 B/s 0.00 bps 0 gas/s CPU: 1%, Mem: 191.2 MiB    
Jan 11 06:19:05.469  WARN sync: Sync: ban a fraudulent peer: ed25519:4ArEQ7ingwWW498H5Mqyf2ZrPvwLnFJyEN4soTgBsnH4@89.58.9.72:24567, claimed height: 57158646    
Jan 11 06:19:05.469  WARN network: Banning peer Some(ed25519:4ArEQ7ingwWW498H5Mqyf2ZrPvwLnFJyEN4soTgBsnH4@89.58.9.72:24567) for HeightFraud
Jan 11 06:19:05.469  WARN network: Banning peer ed25519:4ArEQ7ingwWW498H5Mqyf2ZrPvwLnFJyEN4soTgBsnH4 for HeightFraud
Jan 11 06:19:10.243  INFO stats: #55243952 Downloading headers 95.96% (1914694)   4/1/40 peers ⬇ 0.3kiB/s ⬆ 56 B/s 0.00 bps 0 gas/s CPU: 1%, Mem: 188.7 MiB    
Jan 11 06:19:20.246  INFO stats: #55243952 Downloading headers 95.96% (1914694)   4/1/40 peers ⬇ 0.3kiB/s ⬆ 66 B/s 0.00 bps 0 gas/s CPU: 1%, Mem: 189.4 MiB    
Jan 11 06:19:25.474  WARN sync: Sync: ban a fraudulent peer: ed25519:GnFck7GLqdBgJ3Q5wB3tLY2NKZwig6ZUcXB19eTDmLaS@34.66.248.249:24567, claimed height: 57158646    
Jan 11 06:19:25.474  WARN network: Banning peer Some(ed25519:GnFck7GLqdBgJ3Q5wB3tLY2NKZwig6ZUcXB19eTDmLaS@34.66.248.249:24567) for HeightFraud
Jan 11 06:19:25.474  WARN network: Banning peer ed25519:GnFck7GLqdBgJ3Q5wB3tLY2NKZwig6ZUcXB19eTDmLaS for HeightFraud
Jan 11 06:19:30.249  INFO stats: #55243952 Downloading headers 95.96% (1914694)   3/1/40 peers ⬇ 0.2kiB/s ⬆ 54 B/s 0.00 bps 0 gas/s CPU: 1%, Mem: 186.4 MiB    
Jan 11 06:19:40.252  INFO stats: #55243952 Downloading headers 95.96% (1914686)   3/1/40 peers ⬇ 0.2kiB/s ⬆ 60 B/s 0.00 bps 0 gas/s CPU: 1%, Mem: 186.8 MiB    
Jan 11 06:19:45.481  WARN sync: Sync: ban a fraudulent peer: ed25519:FP6FY95aTzGDhdcbVJjr9a8HQcgm4gDYZFiyYY3XbA7R@116.202.131.161:24567, claimed height: 57158638    
Jan 11 06:19:45.481  WARN network: Banning peer Some(ed25519:FP6FY95aTzGDhdcbVJjr9a8HQcgm4gDYZFiyYY3XbA7R@116.202.131.161:24567) for HeightFraud
Jan 11 06:19:45.481  WARN network: Banning peer ed25519:FP6FY95aTzGDhdcbVJjr9a8HQcgm4gDYZFiyYY3XbA7R for HeightFraud
Jan 11 06:19:50.255  INFO stats: #55243952 Downloading headers 95.96% (1914686)   2/1/40 peers ⬇ 0.1kiB/s ⬆ 28 B/s 0.00 bps 0 gas/s CPU: 1%, Mem: 184.0 MiB    
Jan 11 06:20:00.258  INFO stats: #55243952 Downloading headers 95.96% (1914677)   2/1/40 peers ⬇ 0.1kiB/s ⬆ 38 B/s 0.00 bps 0 gas/s CPU: 1%, Mem: 183.9 MiB    
Jan 11 06:20:05.484  WARN sync: Sync: ban a fraudulent peer: ed25519:6Gj8MRp9KqfdiXa35LJcZnqeBNNEZoYk6ysvpzHaruvq@135.181.130.114:24567, claimed height: 57158629    
Jan 11 06:20:05.485  WARN network: Banning peer Some(ed25519:6Gj8MRp9KqfdiXa35LJcZnqeBNNEZoYk6ysvpzHaruvq@135.181.130.114:24567) for HeightFraud
Jan 11 06:20:05.485  WARN network: Banning peer ed25519:6Gj8MRp9KqfdiXa35LJcZnqeBNNEZoYk6ysvpzHaruvq for HeightFraud
Jan 11 06:20:10.261  INFO stats: #55243952 Cbt4wMBApTG1p3m9W2Uevnzj6d37bzKrYJ3CV7Nbygpp -/59  1/1/40 peers ⬇ 9 B/s ⬆ 14 B/s 0.00 bps 0 gas/s CPU: 1%, Mem: 181.3 MiB    
Jan 11 06:20:20.264  INFO stats: #55243952 Downloading headers 95.95% (1914905)   2/1/40 peers ⬇ 0.1kiB/s ⬆ 0.1kiB/s 0.00 bps 0 gas/s CPU: 1%, Mem: 182.1 MiB    
Jan 11 06:20:25.563  WARN sync: Sync: ban a fraudulent peer: ed25519:9ravz6YFcUhcM6w6s2DPoBhWHmr4rAJNSLQvPNgQcFHE@170.106.163.138:24567, claimed height: 57158857    
Jan 11 06:20:25.563  WARN network: Banning peer Some(ed25519:9ravz6YFcUhcM6w6s2DPoBhWHmr4rAJNSLQvPNgQcFHE@170.106.163.138:24567) for HeightFraud
Jan 11 06:20:25.563  WARN network: Banning peer ed25519:9ravz6YFcUhcM6w6s2DPoBhWHmr4rAJNSLQvPNgQcFHE for HeightFraud
Jan 11 06:20:30.267  INFO stats: #55243952 Cbt4wMBApTG1p3m9W2Uevnzj6d37bzKrYJ3CV7Nbygpp -/59  1/1/40 peers ⬇ 9 B/s ⬆ 25 B/s 0.00 bps 0 gas/s CPU: 1%, Mem: 180.8 MiB    
Jan 11 06:20:40.270  INFO stats: #55243952 Cbt4wMBApTG1p3m9W2Uevnzj6d37bzKrYJ3CV7Nbygpp -/59  1/1/40 peers ⬇ 9 B/s ⬆ 25 B/s 0.00 bps 0 gas/s CPU: 1%, Mem: 181.1 MiB    
Jan 11 06:20:50.272  INFO stats: #55243952 Cbt4wMBApTG1p3m9W2Uevnzj6d37bzKrYJ3CV7Nbygpp -/59  1/1/40 peers ⬇ 9 B/s ⬆ 25 B/s 0.00 bps 0 gas/s CPU: 0%, Mem: 181.3 MiB    
Jan 11 06:21:00.275  INFO stats: #55243952 Cbt4wMBApTG1p3m9W2Uevnzj6d37bzKrYJ3CV7Nbygpp -/59  1/1/40 peers ⬇ 9 B/s ⬆ 25 B/s 0.00 bps 0 gas/s CPU: 1%, Mem: 181.2 MiB    
Jan 11 06:21:10.278  INFO stats: #55243952 Cbt4wMBApTG1p3m9W2Uevnzj6d37bzKrYJ3CV7Nbygpp -/59  1/1/40 peers ⬇ 9 B/s ⬆ 25 B/s 0.00 bps 0 gas/s CPU: 1%, Mem: 181.4 MiB    
Jan 11 06:21:20.280  INFO stats: #55243952 Cbt4wMBApTG1p3m9W2Uevnzj6d37bzKrYJ3CV7Nbygpp -/59  1/1/40 peers ⬇ 9 B/s ⬆ 25 B/s 0.00 bps 0 gas/s CPU: 0%, Mem: 185.4 MiB    
Jan 11 06:21:30.283  INFO stats: #55243952 Cbt4wMBApTG1p3m9W2Uevnzj6d37bzKrYJ3CV7Nbygpp -/59  1/1/40 peers ⬇ 9 B/s ⬆ 25 B/s 0.00 bps 0 gas/s CPU: 1%, Mem: 185.3 MiB    
Jan 11 06:21:40.286  INFO stats: #55243952 Cbt4wMBApTG1p3m9W2Uevnzj6d37bzKrYJ3CV7Nbygpp -/59  1/1/40 peers ⬇ 9 B/s ⬆ 25 B/s 0.00 bps 0 gas/s CPU: 0%, Mem: 185.8 MiB    
Jan 11 06:21:50.289  INFO stats: #55243952 Cbt4wMBApTG1p3m9W2Uevnzj6d37bzKrYJ3CV7Nbygpp -/59  1/1/40 peers ⬇ 9 B/s ⬆ 25 B/s 0.00 bps 0 gas/s CPU: 1%, Mem: 185.8 MiB    
Jan 11 06:22:00.292  INFO stats: #55243952 Cbt4wMBApTG1p3m9W2Uevnzj6d37bzKrYJ3CV7Nbygpp -/59  1/1/40 peers ⬇ 9 B/s ⬆ 25 B/s 0.00 bps 0 gas/s CPU: 0%, Mem: 186.0 MiB    
Jan 11 06:22:10.295  INFO stats: #55243952 Cbt4wMBApTG1p3m9W2Uevnzj6d37bzKrYJ3CV7Nbygpp -/59  1/1/40 peers ⬇ 9 B/s ⬆ 25 B/s 0.00 bps 0 gas/s CPU: 0%, Mem: 185.9 MiB    
Jan 11 06:22:20.298  INFO stats: #55243952 Cbt4wMBApTG1p3m9W2Uevnzj6d37bzKrYJ3CV7Nbygpp -/59  1/1/40 peers ⬇ 9 B/s ⬆ 25 B/s 0.00 bps 0 gas/s CPU: 0%, Mem: 186.0 MiB    
Jan 11 06:22:30.301  INFO stats: #55243952 Cbt4wMBApTG1p3m9W2Uevnzj6d37bzKrYJ3CV7Nbygpp -/59  1/1/40 peers ⬇ 9 B/s ⬆ 25 B/s 0.00 bps 0 gas/s CPU: 0%, Mem: 186.0 MiB    
Jan 11 06:22:40.305  INFO stats: #55243952 Cbt4wMBApTG1p3m9W2Uevnzj6d37bzKrYJ3CV7Nbygpp -/59  1/1/40 peers ⬇ 9 B/s ⬆ 25 B/s 0.00 bps 0 gas/s CPU: 0%, Mem: 186.2 MiB

**Comment by wangtao19911111** [comment] 2022-01-11 06:37
wath can i do something?

**Comment by wangtao19911111** [comment] 2022-01-11 06:38
what can i do something?

**Comment by mintiayields** [comment] 2022-01-11 15:33
This is more of a Discord question than a github bug report. Your possible reasons are (in descending probability):
1. corrupted database as you are stick on the same block
2. wrong (changed) validator_key.json and/or node_key.json.
Again, I think you should turn to Discord for support.

**Comment by janewang** [comment] 2022-01-11 20:19
@wangtao19911111 Please follow the issue reporting format. This issue is likely due to setup. Could you ask in the OSA support testnet-support channel

**Comment by janewang** [comment] 2022-01-11 20:20
Closing as it is not a bug.

**Closed by janewang** 2022-01-11 20:20 UTC
