### ISSUE TITLE
The near daemon may have memory leak

### ISSUE THREAD

**Issue by lcgogo** [near/nearcore#3523] opened 2020-10-23 03:56 UTC
**Describe the bug**
Memory usage increases quickly, I use 1.17-beta2

<img width="758" alt="图片" src="https://user-images.githubusercontent.com/8175573/96954748-9eacd700-1526-11eb-99ae-d7a24c7e92a5.png">

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
- nearcore 1.17.0-beta.2
- rust version (if local)
- docker (if using docker)
- mainnet

**Additional context**

**Comment by bowenwang1996** [comment] 2020-10-23 04:29
duplicate of #2755

**Closed by bowenwang1996** 2020-10-23 04:29 UTC
