### ISSUE TITLE
cargo test routing::archival_node is flaky

### ISSUE THREAD

**Issue by mzhangmzz** [near/nearcore#5718] opened 2021-12-08 15:55 UTC
https://buildkite.com/nearprotocol/nearcore/builds/9453#6e6adde1-1fe4-461f-be1b-99052ce0f804
I ran the test on master branch locally and it failed too

**Comment by mzhangmzz** [comment] 2021-12-08 15:55
@mm-near @pmnoxx do you have an idea why it failed

**Comment by bowenwang1996** [comment] 2021-12-08 19:29
Duplicate of #5357

**Closed by bowenwang1996** 2021-12-08 19:29 UTC

**Comment by pmnoxx** [comment] 2021-12-08 20:13
@bowenwang1996 I already wrote a fix: https://github.com/near/nearcore/pull/5639
