### ISSUE TITLE
neard fails to restart after a clean shutdown (data corruption)

### ISSUE THREAD

**Issue by i-love-to-code** [near/nearcore#3713] opened 2020-12-08 06:28 UTC
**Describe the bug**
Corrupted database after a shutdown. Logs indicate shutdown was clean, however error shown when trying to restart the node.

**To Reproduce**
1. `neard run & echo $! > neard.pid`
2. ``kill -SIGTERM `cat nead.pid` ``
3. `neard run`

**Expected behavior**
neard starts after a clean shutsdown.

**Screenshots**

LOG
```
2020/12/06-13:01:45.738080 7fd8149662c0 [db/column_family.cc:583] 	(skipping printing options)
2020/12/06-13:01:45.738171 7fd8149662c0 [db/column_family.cc:583] 	(skipping printing options)
2020/12/06-13:01:45.738181 7fd8149662c0 [db/column_family.cc:583] 	(skipping printing options)
2020/12/06-13:01:45.738203 7fd8149662c0 [db/column_family.cc:583] 	(skipping printing options)
2020/12/06-13:01:45.738214 7fd8149662c0 [db/column_family.cc:583] 	(skipping printing options)
2020/12/06-13:01:45.738224 7fd8149662c0 [db/column_family.cc:583] 	(skipping printing options)
2020/12/06-13:01:45.738233 7fd8149662c0 [db/column_family.cc:583] 	(skipping printing options)
2020/12/06-13:01:45.738242 7fd8149662c0 [db/column_family.cc:583] 	(skipping printing options)
2020/12/06-13:01:45.741194 7fd8149662c0 [db/db_impl/db_impl.cc:438] Shutdown: canceling all background work
2020/12/06-13:01:45.741393 7fd8149662c0 [db/db_impl/db_impl.cc:614] Shutdown complete
```

Startup
```
$ ./neard run
Dec 06 11:55:53.234 INFO near: Version: 1.16.2, Build: 76dSa036, Latest Protocol: 40
Dec 06 11:55:53.237 INFO near: Opening store database at "/hone/eosdublin/.near/data"
thread 'main' panicked at 'Failed to open the database: DBError(Error { message: "IO error: No such file or directoryWhile open a file for random read: /hone/eosdublin/.
near/data/012157.ldb: No such file or directory"}); core/store/src/lib.rs:289:23
note: run with `RUST BACKTRACE=1` environment variable to display a backtrace
```

Directory Contents
```
000096.sst  008259.sst  008891.sst  009314.sst  009489.sst  009665.sst  009834.sst  009959.sst  010155.sst  010261.sst  010411.sst  010542.sst  010686.sst  010820.sst  011346.sst  011711.sst  012012.sst  012136.sst
000102.sst  008283.sst  008892.sst  009315.sst  009490.sst  009697.sst  009835.sst  009960.sst  010156.sst  010262.sst  010412.sst  010543.sst  010687.sst  010821.sst  011347.sst  011712.sst  012013.sst  012139.sst
000105.sst  008284.sst  008893.sst  009316.sst  009491.sst  009698.sst  009839.sst  009961.sst  010157.sst  010263.sst  010413.sst  010544.sst  010688.sst  010822.sst  011348.sst  011827.sst  012043.sst  012140.sst
000108.sst  008285.sst  008947.sst  009317.sst  009492.sst  009699.sst  009840.sst  010000.sst  010158.sst  010264.sst  010414.sst  010545.sst  010689.sst  010823.sst  011349.sst  011832.sst  012046.sst  012141.sst
000111.sst  008286.sst  009000.sst  009318.sst  009493.sst  009700.sst  009841.sst  010001.sst  010159.sst  010265.sst  010415.sst  010546.sst  010726.sst  010861.sst  011350.sst  011900.sst  012047.sst  012142.log
002517.sst  008324.sst  009001.sst  009319.sst  009495.sst  009701.sst  009842.sst  010002.sst  010170.sst  010282.sst  010416.sst  010557.sst  010727.sst  010862.sst  011352.sst  011902.sst  012048.sst  012144.log
005358.sst  008325.sst  009002.sst  009320.sst  009496.sst  009702.sst  009843.sst  010003.sst  010171.sst  010283.sst  010441.sst  010558.sst  010728.sst  010863.sst  011353.sst  011903.sst  012049.sst  012145.log
005519.sst  008439.sst  009047.sst  009321.sst  009497.sst  009705.sst  009844.sst  010004.sst  010172.sst  010284.sst  010442.sst  010559.sst  010729.sst  010864.sst  011354.sst  011905.sst  012050.sst  012146.sst
006859.sst  008452.sst  009048.sst  009322.sst  009498.sst  009706.sst  009856.sst  010005.sst  010173.sst  010285.sst  010443.sst  010560.sst  010730.sst  010865.sst  011355.sst  011906.sst  012051.sst  012147.log
006860.sst  008466.sst  009056.sst  009362.sst  009499.sst  009708.sst  009857.sst  010006.sst  010174.sst  010286.sst  010444.sst  010561.sst  010731.sst  010867.sst  011356.sst  011907.sst  012052.sst  012150.log
007068.sst  008467.sst  009116.sst  009363.sst  009500.sst  009709.sst  009858.sst  010007.sst  010175.sst  010287.sst  010445.sst  010562.sst  010732.sst  010868.sst  011357.sst  011908.sst  012053.sst  012152.sst
007789.sst  008468.sst  009117.sst  009364.sst  009501.sst  009710.sst  009859.sst  010017.sst  010176.sst  010288.sst  010446.sst  010563.sst  010733.sst  010869.sst  011358.sst  011909.sst  012060.sst  012153.sst
007790.sst  008469.sst  009118.sst  009365.sst  009512.sst  009711.sst  009860.sst  010018.sst  010178.sst  010289.sst  010463.sst  010592.sst  010734.sst  010870.sst  011359.sst  011910.sst  012063.sst  012154.log
007791.sst  008497.sst  009119.sst  009366.sst  009513.sst  009712.sst  009861.sst  010019.sst  010179.sst  010313.sst  010464.sst  010593.sst  010735.sst  010871.sst  011360.sst  011911.sst  012064.sst  012155.log
007792.sst  008603.sst  009120.sst  009367.sst  009514.sst  009723.sst  009862.sst  010020.sst  010181.sst  010314.sst  010465.sst  010594.sst  010736.sst  010872.sst  011361.sst  011912.sst  012067.sst  012157.log
007793.sst  008604.sst  009121.sst  009390.sst  009515.sst  009726.sst  009904.sst  010021.sst  010182.sst  010315.sst  010466.sst  010595.sst  010737.sst  010873.sst  011624.sst  011913.sst  012070.sst  012158.log
007794.sst  008605.sst  009122.sst  009391.sst  009516.sst  009727.sst  009905.sst  010022.sst  010183.sst  010316.sst  010467.sst  010596.sst  010738.sst  010874.sst  011628.sst  011914.sst  012071.sst  012160.sst
008009.sst  008606.sst  009166.sst  009392.sst  009537.sst  009728.sst  009906.sst  010060.sst  010184.sst  010317.sst  010468.sst  010597.sst  010739.sst  010875.sst  011651.sst  011915.sst  012072.sst  CURRENT
008010.sst  008607.sst  009188.sst  009393.sst  009538.sst  009729.sst  009907.sst  010061.sst  010185.sst  010318.sst  010469.sst  010598.sst  010750.sst  010909.sst  011684.sst  011918.sst  012085.sst  IDENTITY
008011.sst  008608.sst  009189.sst  009394.sst  009577.sst  009730.sst  009908.sst  010062.sst  010186.sst  010319.sst  010470.sst  010618.sst  010751.sst  010910.sst  011685.sst  011919.sst  012088.sst  LOCK
008012.sst  008632.sst  009206.sst  009395.sst  009578.sst  009731.sst  009909.sst  010063.sst  010187.sst  010332.sst  010495.sst  010619.sst  010752.sst  010913.sst  011686.sst  011920.sst  012094.sst  LOCK.BAK
008013.sst  008633.sst  009207.sst  009412.sst  009579.sst  009758.sst  009911.sst  010064.sst  010206.sst  010333.sst  010496.sst  010620.sst  010779.sst  010914.sst  011687.sst  011921.sst  012096.sst  LOCKBAK2
008014.sst  008634.sst  009208.sst  009413.sst  009580.sst  009759.sst  009912.sst  010065.sst  010207.sst  010335.sst  010497.sst  010621.sst  010780.sst  010918.sst  011688.sst  011922.sst  012097.sst  LOG
008018.sst  008645.sst  009209.sst  009414.sst  009583.sst  009760.sst  009913.sst  010066.sst  010208.sst  010336.sst  010498.sst  010622.sst  010781.sst  010924.sst  011689.sst  011923.sst  012098.sst  LOG.old.1607252062570186
008020.sst  008646.sst  009210.sst  009415.sst  009584.sst  009761.sst  009914.sst  010067.sst  010209.sst  010337.sst  010499.sst  010623.sst  010782.sst  010925.sst  011691.sst  011924.sst  012099.sst  LOG.old.1607252062835629
008099.sst  008647.sst  009224.sst  009416.sst  009585.sst  009762.sst  009915.sst  010094.sst  010210.sst  010338.sst  010500.sst  010624.sst  010783.sst  010952.sst  011693.sst  011925.sst  012100.sst  LOG.old.1607252118666042
008114.sst  008773.sst  009225.sst  009417.sst  009586.sst  009763.sst  009917.sst  010095.sst  010211.sst  010339.sst  010520.sst  010632.sst  010784.sst  010953.sst  011694.sst  011926.sst  012101.sst  LOG.old.1607252118904539
008115.sst  008797.sst  009226.sst  009418.sst  009587.sst  009772.sst  009918.sst  010096.sst  010212.sst  010370.sst  010521.sst  010633.sst  010800.sst  010954.sst  011696.sst  011927.sst  012102.sst  LOG.old.1607252130356878
008116.sst  008798.sst  009227.sst  009449.sst  009588.sst  009773.sst  009919.sst  010097.sst  010213.sst  010371.sst  010522.sst  010634.sst  010801.sst  010961.sst  011697.sst  011928.sst  012103.sst  LOG.old.1607252130598967
008117.sst  008799.sst  009228.sst  009450.sst  009618.sst  009774.sst  009920.sst  010098.sst  010222.sst  010372.sst  010523.sst  010635.sst  010802.sst  010962.sst  011698.sst  011929.sst  012113.sst  LOG.old.1607252153238132
008118.sst  008822.sst  009245.sst  009451.sst  009619.sst  009775.sst  009921.sst  010099.sst  010223.sst  010373.sst  010524.sst  010636.sst  010804.sst  010963.sst  011699.sst  011947.sst  012114.sst  LOG.old.1607252153473578
008119.sst  008839.sst  009246.sst  009452.sst  009620.sst  009790.sst  009922.sst  010100.sst  010224.sst  010374.sst  010525.sst  010637.sst  010805.sst  011050.sst  011700.sst  011948.sst  012118.sst  LOG.old.1607252253793338
008129.sst  008840.sst  009247.sst  009453.sst  009621.sst  009791.sst  009923.sst  010107.sst  010225.sst  010375.sst  010532.sst  010638.sst  010808.sst  011333.sst  011701.sst  011949.sst  012120.sst  LOG.old.1607252254019616
008130.sst  008841.sst  009248.sst  009455.sst  009622.sst  009792.sst  009933.sst  010108.sst  010226.sst  010387.sst  010533.sst  010639.sst  010809.sst  011334.sst  011702.sst  011950.sst  012121.sst  LOG.old.1607256105472847
008131.sst  008842.sst  009249.sst  009456.sst  009623.sst  009793.sst  009934.sst  010109.sst  010227.sst  010388.sst  010534.sst  010655.sst  010810.sst  011335.sst  011703.sst  011951.sst  012125.sst  LOG.old.1607256105735330
008132.sst  008872.sst  009286.sst  009457.sst  009632.sst  009794.sst  009935.sst  010110.sst  010228.sst  010389.sst  010535.sst  010656.sst  010813.sst  011337.sst  011704.sst  011952.sst  012126.sst  MANIFEST-012153
008133.sst  008873.sst  009287.sst  009458.sst  009633.sst  009795.sst  009936.sst  010111.sst  010229.sst  010390.sst  010536.sst  010657.sst  010814.sst  011338.sst  011705.sst  011953.sst  012127.log  OPTIONS-000118
008134.sst  008874.sst  009288.sst  009459.sst  009634.sst  009796.sst  009937.sst  010112.sst  010256.sst  010391.sst  010537.sst  010658.sst  010815.sst  011339.sst  011706.sst  011954.sst  012128.log  OPTIONS-012156
008135.sst  008875.sst  009310.sst  009460.sst  009635.sst  009797.sst  009938.sst  010143.sst  **010257.sst**  010392.sst  010538.sst  010682.sst  010816.sst  011340.sst  011707.sst  011955.sst  012131.log
008160.sst  008888.sst  009311.sst  009486.sst  009636.sst  009831.sst  009956.sst  010144.sst  010258.sst  010393.sst  010539.sst  010683.sst  010817.sst  011341.sst  011708.sst  011968.sst  012132.log
008255.sst  008889.sst  009312.sst  009487.sst  009637.sst  009832.sst  009957.sst  010145.sst  010259.sst  010408.sst  010540.sst  010684.sst  010818.sst  011342.sst  011709.sst  011973.sst  012134.sst
008256.sst  008890.sst  009313.sst  009488.sst  009638.sst  009833.sst  009958.sst  010146.sst  010260.sst  010409.sst  010541.sst  010685.sst  010819.sst  011343.sst  011710.sst  011989.sst  012135.sst
```

**Version (please complete the following information):**
- nearcore: 1.16.2
- rust version: nightly-2020-05-15
- docker: NO
- mainnet

**Additional context**
Node had been running for a while. Clean shutdown initiated (SIGTERM) which appeared to work, however attempts to restart the node resulted in an IO error (see screenshots above). The complete data directory has been archived if this would prove useful in diagnosing the issue.

**Comment by bowenwang1996** [comment] 2021-06-29 00:18
Duplicate of #3266

**Closed by bowenwang1996** 2021-06-29 00:18 UTC
