### ISSUE TITLE
[stateless_validation] Limit witness size growth on large incoming receipts

### ISSUE THREAD

**Issue by wacban** [near/nearcore#11383] opened 2024-05-23 09:51 UTC
Due to `source_receipt_proofs` field, state witness size can become too large to be distributed in time for validation. The `source_receipt_proofs` of shard S are derived from the outgoing receipts from other shards with receiver in S. 

This is a follow up of #11039 where we limited the impact of shard needing to collect receipts from all the blocks where it missed a chunk. Currently shards will stop sending any new receipts once the target shard has 10 or more missing chunks in a row. This constant can just further adjusted if needed. 

The remaining issue is that the `source_receipts_proofs` can become too large just in a single block, without any missing chunks. This can happen e.g. when all other shards all send multiple large receipts to a single receiver. 

The goal for this issue is to mitigate this problem.

**Comment by jancionear** [comment] 2024-05-23 09:53
Isn't that a duplicate of https://github.com/near/nearcore/issues/11295?

**Comment by wacban** [comment] 2024-05-23 09:55
Ah yeah it seems like it. I thought we needed a new issue for that based on [that](https://github.com/near/nearcore/issues/11039#issuecomment-2123020716) comment. Let me close this in favour of the other one.

**Closed** 2024-05-23 09:55 UTC
Labels: T-core, Near Core, A-stateless-validation
