### ISSUE TITLE
Nodes often go out of sync 

### ISSUE THREAD

**Issue by frol** [near/nearcore#4937] opened 2021-10-05 18:03 UTC
**Describe the bug**

After a recent release we observe that nearcore nodes often fall behind syncing (it is just a few blocks behind, but it is still suspicious and also causes problems down the line in the Indexer).

mainnet:

![image](https://user-images.githubusercontent.com/304265/136077645-0cf7ffa0-dce1-4143-bd2d-46a6f29065fa.png)

testnet:

![image](https://user-images.githubusercontent.com/304265/136077675-fe2deade-f8fa-46f9-bcaf-24145c225176.png)

Also, it seems to use more CPU and view-client is bounded by a single CPU.

**To Reproduce**

N/A

**Expected behavior**

Don't fall behind the network.

**Version (please complete the following information):**

- nearcore commit/branch: 1.21.1
- mainnet and testnet

**Comment by frol** [comment] 2021-10-05 18:10
Sometimes nearcore completely utilizes a single CPU core and doesn't get anywhere beyond that. This congestion throttles view-client that we use inside Indexer Framework, and Indexer for Explorer lags behind on indexing the data to Postgres.

An interesting observation so far is that when I try to kill an indexer node (which embeds nearcore), it does not stop completely, it only stops some of the actors and this lets Indexer to process all the blocks at 6 bps until it reaches the block height where I killed the process, so sync was not working, but view-client and indexer still worked, and here is the twist (!): after indexer reached the end, there should be no work going on the process, but it still consumes 33% of a single core, so I went ahead to inspected it with flamegraph and it shows that the program spends half of the time in  `near_chain::store::ChainStore::iterate_state_sync_infos` (inside `near_client::client::Client::run_catchup`) even though I can see that the actual catchup does not happen!

[flamegraph.svg.zip](https://github.com/near/nearcore/files/7288223/flamegraph.svg.zip)

**Comment by bowenwang1996** [comment] 2021-10-06 10:43
I looked at the use of `StateSyncInfo` and did not find anything that is obviously wrong. We do remove state download info in `catchup_blocks`. We need to dump the database column to see what is in there and it may be related to #1153

**Comment by mina86** [comment] 2021-10-13 00:21
> An interesting observation so far is that when I try to kill an indexer node (which embeds nearcore), it does not stop completely

I’ve filed https://github.com/near/nearcore/issues/4994 for that.

**Comment by mina86** [comment] 2021-11-16 15:43
Closing as duplicate of https://github.com/near/nearcore/issues/5112

**Closed by mina86** 2021-11-16 15:43 UTC
Labels: A-chain, P-critical, C-incident, T-core
