### ISSUE TITLE
`cargo test --all` fails on macos M1 devices

### ISSUE THREAD

**Issue by topSkr** [near/nearcore#8074] opened 2022-11-17 08:33 UTC
An error is reported in test cargo test --all. The device used is macos M1

Compiling heck v0.3.3
error[E0425]: cannot find function `get_fault_info` in this scope
   --> /Users/wangjiawei/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-runtime-core-near-0.17.4/src/fault.rs:296:21
    |
296 |         let fault = get_fault_info(siginfo as  _, ucontext);
    |                     ^^^^^^^^^^^^^^ not found in this scope

**Comment by akhi3030** [comment] 2022-11-17 09:14
Thanks for creating the issue.  I have an M1 device.  Let me see if I can reproduce it.

**Comment by akhi3030** [comment] 2022-11-17 09:19
@topSkr: I could not reproduce the compiler error on my machine.  Can you please try the following steps:
- Make sure that you are using the top of the master.  Please post the commit hash that you tested with.
- Please run `cargo clean` just in case somehow your build directory got into a bad state and then retry.

**Comment by mrthankyou** [comment] 2023-01-17 23:51
@akhi3030,

I can produce this with running Ref Finance's [repo](https://github.com/ref-finance/ref-contracts) `cargo test --all` command. I also ran cargo clean before calling cargo test. Ref Finance commit in my local machine is at 19e98ec7e70b72d0a2bb1281eb8cd171cebcc931. 

Any help on this would be great! Thank you!

**Comment by akhi3030** [comment] 2023-01-24 13:54
Hey @mrthankyou.  I think I might need more context here.  If this error is happening on ref finance's repo, shouldn't this issue exist there and be debugged there?  If they are using a fork of this repo, they may not have all the latest changes which might be causing this issue.  We have definitely had problems with M1 devices in the past but are not aware of any open issues on top of the tree.

**Comment by mrthankyou** [comment] 2023-01-26 19:38
The error occurs when running Ref Finance. My made an assumption (possibly a bad one) that the error is consistent between Ref and NearCore.

I will discuss with the Ref Finance team about this bug. Thanks for the help.

**Comment by akhi3030** [comment] 2023-01-27 09:37
Anytime.  I'll close the issue for now.  Please reopen or create a new issue as needed.

**Closed by akhi3030** 2023-01-27 09:37 UTC
