### ISSUE TITLE
Integration tests are inconvenient

### ISSUE THREAD

**Issue by Longarithm** [near/nearcore#4305] opened 2021-05-19 13:01 UTC
When adding a test for `chain/client/tests/process_blocks.rs` and trying to access private field of `NightshadeRuntime`, I've noticed that `#[cfg(test)]` doesn't work.

The reason for that is that it's an integrated test: for them libraries are built without `#[cfg(test)]`. If it was a unit test, it would be simpler to test `NightshadeRuntime` functionality.

@matklad also notices that our chain tests depend on the whole neard, which creates cyclic dependencies.
There's also an observation that many integrated tests hurt compile times.

**Comment by bowenwang1996** [comment] 2021-05-19 15:15
Yes some of the tests should not be placed in that file. However, even if we place them somewhere else (as integration tests), you still won't be able to access the private fields of `NightshadeRuntime`.

**Comment by Longarithm** [comment] 2021-05-19 15:25
Yeah, I wanted to say that I could write a public method of `NightshadeRuntime` accessing private field and add `#[cfg(test)]` to it.

**Comment by bowenwang1996** [comment] 2021-06-28 20:31
Duplicate of #4357

**Closed by bowenwang1996** 2021-06-28 20:31 UTC
