### ISSUE TITLE
Investigate a discrepancy between runtime config values in rosetta RPC vs JSON RPC

### ISSUE THREAD

**Issue by frol** [near/nearcore#5197] opened 2021-11-10 18:42 UTC
Initiating a new localnet node (1.21.0 release) with the default genesis sets the storage price per byte to 90900000000000000000, but then JSON RPC allegedly reports it to be 10^20. https://github.com/near/nearcore/issues/5086#issuecomment-965397406

> I see this value 90900000000000000000 as amount that rosetta is reporting as LIQUID_BALANCE_FOR_STORAGE (182 * 9.09 × 10^19)
> the other value I see from near rpc endpoint EXPERIMENTAL_protocol_config

**Comment by bowenwang1996** [comment] 2022-02-21 23:58
@frol @mina86 what is the status of this issue? Did we fix it?

**Comment by frol** [comment] 2022-03-22 11:56
Nope, it was not investigated further. @mina86 Could you take a closer look if the issue is reproducible these days once you have some time?

**Comment by mina86** [comment] 2022-03-22 15:57
I’ll assign it to myself not to forget, but haven’t looked at it and most likely won’t in the next few weeks.

**Comment by firatNEAR** [comment] 2022-04-20 09:13
Are we looking to reproduce the issue on the latest version of the protocol or with version 1.21.release?

**Comment by mina86** [comment] 2022-04-20 15:18
Latest version.

**Comment by firatNEAR** [comment] 2022-04-20 15:28
**Version** 
nearcore tag latest
rustc 1.59.0
rustup 1.24.3
cargo 1.59.0
local env with local network
neard was compiled with --features rosetta_rpc and started with rosetta api enabled in conf file
using default genesis.json

```
rosetta-rpc git:(master) ✗ ./bin/rosetta-cli-0.7.5-darwin-amd64 --configuration-file ./rosetta-localnet.cfg view:balance '{"address": "fomo.test.near", "sub_account": {"address": "LIQUID_BALANCE_FOR_STORAGE"}}'
loaded configuration file: ./rosetta-localnet.cfg
2022/04/20 16:43:17 Amounts: [
 {
  "value": "1820000000000000000000",
  "currency": {
   "symbol": "NEAR",
   "decimals": 24
  }
 }
]
2022/04/20 16:43:17 Metadata: null
2022/04/20 16:43:17 Balance Fetched At: {
 "index": 15284,
 "hash": "7rnFzMCEX8AmbMUzhAtCg3WajS3uk3EQ4hdyHgBhsjSw"
}

rosetta-rpc git:(master) ✗ ./bin/rosetta-cli-0.7.5-darwin-amd64 --configuration-file rosetta-localnet.cfg view:balance '{"address": "fomo.test.near"}'
loaded configuration file: rosetta-localnet.cfg
2022/04/20 16:44:17 Amounts: [
 {
  "value": "49998180000000000000000000",
  "currency": {
   "symbol": "NEAR",
   "decimals": 24
  }
 }
]
2022/04/20 16:44:17 Metadata: null
2022/04/20 16:44:17 Balance Fetched At: {
 "index": 15380,
 "hash": "D2AUBGmLmWs24bEn7sEprwUsQ2NbzZfcqFrcapa2Yqtv"
}

curl http://localhost:3030 -H 'Content-Type: application/json' --data '{"jsonrpc": "2.0", "method": "query", "params": {"request_type": "view_account", "account_id": "fomo.test.near", "finality": "final"}, "id": "dontcare"}'

\{"jsonrpc":"2.0","result":{"amount":"50000000000000000000000000","block_hash":"HWstv8D2r6aib3jNFWnYN8hsEf551bE8arWgpyv2CBxm","block_height":15484,"code_hash":"11111111111111111111111111111111","locked":"0","storage_paid_at":0,"storage_usage":182},"id":"dontcare"}
  
```
It looks to me that the issue is not there anymore in latest release

**Comment by frol** [comment] 2022-04-20 19:20
@firatNEAR Can you set `"storage_amount_per_byte": "90900000000000000000"` in the genesis.json and see if the discrepancy will be there?

**Comment by firatNEAR** [comment] 2022-04-22 10:27
`"storage_amount_per_byte": "90900000000000000000"` Doesn't seem to persist even if I change the genesis.json accordingly. 


`http post http://localhost:3030 jsonrpc=2.0 id=dontcare method=EXPERIMENTAL_protocol_config \
  params:='{
    "finality": "final"
  }'`
  still returns `"storage_amount_per_byte": "10000000000000000000"`
  
  
  rosetta RPC returns `2022/04/22 12:24:00 Amounts: [
 {
  "value": "1820000000000000000000",
  "currency": {
   "symbol": "NEAR",
   "decimals": 24
  }
 }
]` for a created account

JSON RPC returns 
`{
    "id": "dontcare",
    "jsonrpc": "2.0",
    "result": {
        "amount": "50000000000000000000000000",
        "block_hash": "Hh6LpJCGD3aGdzdUGCZd639t3kVbYxD4vUfXSeWK8p7j",
        "block_height": 963,
        "code_hash": "11111111111111111111111111111111",
        "locked": "0",
        "storage_paid_at": 0,
        "storage_usage": 182
    }
}`

**Comment by firatNEAR** [comment] 2022-04-24 14:56
Since the discrepancy is not there anymore with the default genesis in latest version of nearcore, I am closing the issue.

**Closed by firatNEAR** 2022-04-24 14:56 UTC
Labels: C-bug, A-RPC
