### ISSUE TITLE
【BUG】near-olly opentelemetry conflicts with the standard library and has been contaminated

### ISSUE THREAD

**Issue by zwong91** [near/nearcore#10390] opened 2024-01-06 10:57 UTC
error[E0659]: `opentelemetry` is ambiguous
  --> /workspace/.cargo/registry/src/index.crates.io-6f17d22bba15001f/near-o11y-0.19.0/src/lib.rs:6:9
   |
6  | pub use opentelemetry::OpenTelemetryLevel;
   |         ^^^^^^^^^^^^^ ambiguous name
   |
   = note: ambiguous because of multiple potential import sources
   = note: `opentelemetry` could refer to a crate passed with `--extern`
   = help: use `::opentelemetry` to refer to this crate unambiguously
note: `opentelemetry` could also refer to the module defined here
  --> /workspace/.cargo/registry/src/index.crates.io-6f17d22bba15001f/near-o11y-0.19.0/src/lib.rs:22:1

**Comment by zwong91** [comment] 2024-01-06 11:16
core/o11y/src/lib.rs
pub use opentelemetry::OpenTelemetryLevel;

crates are contaminated and cannot be identified, should be replaced with the next, for example:

use crate::opentelemetry as near_opentelemetry;
pub use near_opentelemetry::OpenTelemetryLevel;

**Comment by nagisa** [comment] 2024-01-08 15:08
Please provide reproduction steps. What are you doing in order to see this error?

**Comment by frol** [comment] 2024-02-22 23:32
@nagisa The root cause is #10477, I will close this issue in favor of that newer and more detailed one.

@zwong91 Use the latest stable Rust version to compile to avoid this error.

**Closed by frol** 2024-02-22 23:32 UTC
